# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gov/llnl/ernie/raven/proto/control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gov/llnl/ernie/raven/proto/control.proto',
  package='gov.llnl.ernie.raven',
  syntax='proto3',
  serialized_options=b'\n\024gov.llnl.ernie.ravenB\rControlProtos',
  serialized_pb=b'\n(gov/llnl/ernie/raven/proto/control.proto\x12\x14gov.llnl.ernie.raven\" \n\rErrorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x10\x43onfigureRequest\x12\r\n\x05lanes\x18\x01 \x01(\x05\"!\n\x11\x43onfigureResponse\x12\x0c\n\x04port\x18\x01 \x03(\x05\"\x0f\n\rStatusRequest\"\x80\x01\n\x0eStatusResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontrol_port\x18\x02 \x01(\x05\x12\x10\n\x08log_port\x18\x03 \x01(\x05\x12\x35\n\x0blane_status\x18\x04 \x03(\x0b\x32 .gov.llnl.ernie.raven.LaneStatus\"B\n\nLaneStatus\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\x10\n\x08messages\x18\x02 \x01(\x05\x12\x14\n\x0clast_scan_id\x18\x03 \x01(\x05\"\x12\n\x10TerminateRequest\"\x13\n\x11TerminateResponseB%\n\x14gov.llnl.ernie.ravenB\rControlProtosb\x06proto3'
)




_ERRORRESPONSE = _descriptor.Descriptor(
  name='ErrorResponse',
  full_name='gov.llnl.ernie.raven.ErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='gov.llnl.ernie.raven.ErrorResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=98,
)


_CONFIGUREREQUEST = _descriptor.Descriptor(
  name='ConfigureRequest',
  full_name='gov.llnl.ernie.raven.ConfigureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lanes', full_name='gov.llnl.ernie.raven.ConfigureRequest.lanes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=133,
)


_CONFIGURERESPONSE = _descriptor.Descriptor(
  name='ConfigureResponse',
  full_name='gov.llnl.ernie.raven.ConfigureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='gov.llnl.ernie.raven.ConfigureResponse.port', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=168,
)


_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='gov.llnl.ernie.raven.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=185,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='gov.llnl.ernie.raven.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='gov.llnl.ernie.raven.StatusResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_port', full_name='gov.llnl.ernie.raven.StatusResponse.control_port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_port', full_name='gov.llnl.ernie.raven.StatusResponse.log_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lane_status', full_name='gov.llnl.ernie.raven.StatusResponse.lane_status', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=316,
)


_LANESTATUS = _descriptor.Descriptor(
  name='LaneStatus',
  full_name='gov.llnl.ernie.raven.LaneStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='gov.llnl.ernie.raven.LaneStatus.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='gov.llnl.ernie.raven.LaneStatus.messages', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_scan_id', full_name='gov.llnl.ernie.raven.LaneStatus.last_scan_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=384,
)


_TERMINATEREQUEST = _descriptor.Descriptor(
  name='TerminateRequest',
  full_name='gov.llnl.ernie.raven.TerminateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=404,
)


_TERMINATERESPONSE = _descriptor.Descriptor(
  name='TerminateResponse',
  full_name='gov.llnl.ernie.raven.TerminateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=425,
)

_STATUSRESPONSE.fields_by_name['lane_status'].message_type = _LANESTATUS
DESCRIPTOR.message_types_by_name['ErrorResponse'] = _ERRORRESPONSE
DESCRIPTOR.message_types_by_name['ConfigureRequest'] = _CONFIGUREREQUEST
DESCRIPTOR.message_types_by_name['ConfigureResponse'] = _CONFIGURERESPONSE
DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['LaneStatus'] = _LANESTATUS
DESCRIPTOR.message_types_by_name['TerminateRequest'] = _TERMINATEREQUEST
DESCRIPTOR.message_types_by_name['TerminateResponse'] = _TERMINATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorResponse = _reflection.GeneratedProtocolMessageType('ErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.ErrorResponse)
  })
_sym_db.RegisterMessage(ErrorResponse)

ConfigureRequest = _reflection.GeneratedProtocolMessageType('ConfigureRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGUREREQUEST,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.ConfigureRequest)
  })
_sym_db.RegisterMessage(ConfigureRequest)

ConfigureResponse = _reflection.GeneratedProtocolMessageType('ConfigureResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURERESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.ConfigureResponse)
  })
_sym_db.RegisterMessage(ConfigureResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

LaneStatus = _reflection.GeneratedProtocolMessageType('LaneStatus', (_message.Message,), {
  'DESCRIPTOR' : _LANESTATUS,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.LaneStatus)
  })
_sym_db.RegisterMessage(LaneStatus)

TerminateRequest = _reflection.GeneratedProtocolMessageType('TerminateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATEREQUEST,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.TerminateRequest)
  })
_sym_db.RegisterMessage(TerminateRequest)

TerminateResponse = _reflection.GeneratedProtocolMessageType('TerminateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATERESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.control_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.TerminateResponse)
  })
_sym_db.RegisterMessage(TerminateResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
