# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gov/llnl/ernie/raven/proto/lane.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gov/llnl/ernie/raven/proto/lane.proto',
  package='gov.llnl.ernie.raven',
  syntax='proto3',
  serialized_options=b'\n\024gov.llnl.ernie.ravenB\nLaneProtos',
  serialized_pb=b'\n%gov/llnl/ernie/raven/proto/lane.proto\x12\x14gov.llnl.ernie.raven\"$\n\x11LaneErrorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x86\x02\n\x14LaneConfigureRequest\x12\x0f\n\x07site_id\x18\x01 \x01(\x05\x12\x0f\n\x07lane_id\x18\x02 \x01(\x05\x12\x12\n\ncollimated\x18\x03 \x01(\x08\x12\x12\n\nlane_width\x18\x04 \x01(\x01\x12\x11\n\tintervals\x18\x05 \x01(\x05\x12\x0e\n\x06holdin\x18\x06 \x01(\x05\x12N\n\nproperties\x18\x07 \x03(\x0b\x32:.gov.llnl.ernie.raven.LaneConfigureRequest.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa1\x01\n\x15LaneConfigureResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12H\n\x07md5_map\x18\x02 \x03(\x0b\x32\x37.gov.llnl.ernie.raven.LaneConfigureResponse.Md5MapEntry\x1a-\n\x0bMd5MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x16ProcessScanDataRequest\x12\x0f\n\x07scan_id\x18\x01 \x01(\x05\x12\x11\n\tscan_data\x18\x02 \x01(\t\"<\n\x17ProcessScanDataResponse\x12\x0f\n\x07scan_id\x18\x01 \x01(\x05\x12\x10\n\x08xml_data\x18\x02 \x01(\tB\"\n\x14gov.llnl.ernie.ravenB\nLaneProtosb\x06proto3'
)




_LANEERRORRESPONSE = _descriptor.Descriptor(
  name='LaneErrorResponse',
  full_name='gov.llnl.ernie.raven.LaneErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='gov.llnl.ernie.raven.LaneErrorResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=99,
)


_LANECONFIGUREREQUEST_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='gov.llnl.ernie.raven.LaneConfigureRequest.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=364,
)

_LANECONFIGUREREQUEST = _descriptor.Descriptor(
  name='LaneConfigureRequest',
  full_name='gov.llnl.ernie.raven.LaneConfigureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_id', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.site_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.lane_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collimated', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.collimated', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lane_width', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.lane_width', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intervals', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.intervals', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='holdin', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.holdin', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='gov.llnl.ernie.raven.LaneConfigureRequest.properties', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LANECONFIGUREREQUEST_PROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=364,
)


_LANECONFIGURERESPONSE_MD5MAPENTRY = _descriptor.Descriptor(
  name='Md5MapEntry',
  full_name='gov.llnl.ernie.raven.LaneConfigureResponse.Md5MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gov.llnl.ernie.raven.LaneConfigureResponse.Md5MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gov.llnl.ernie.raven.LaneConfigureResponse.Md5MapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=528,
)

_LANECONFIGURERESPONSE = _descriptor.Descriptor(
  name='LaneConfigureResponse',
  full_name='gov.llnl.ernie.raven.LaneConfigureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='gov.llnl.ernie.raven.LaneConfigureResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='md5_map', full_name='gov.llnl.ernie.raven.LaneConfigureResponse.md5_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LANECONFIGURERESPONSE_MD5MAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=528,
)


_PROCESSSCANDATAREQUEST = _descriptor.Descriptor(
  name='ProcessScanDataRequest',
  full_name='gov.llnl.ernie.raven.ProcessScanDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_id', full_name='gov.llnl.ernie.raven.ProcessScanDataRequest.scan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scan_data', full_name='gov.llnl.ernie.raven.ProcessScanDataRequest.scan_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=590,
)


_PROCESSSCANDATARESPONSE = _descriptor.Descriptor(
  name='ProcessScanDataResponse',
  full_name='gov.llnl.ernie.raven.ProcessScanDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_id', full_name='gov.llnl.ernie.raven.ProcessScanDataResponse.scan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xml_data', full_name='gov.llnl.ernie.raven.ProcessScanDataResponse.xml_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=652,
)

_LANECONFIGUREREQUEST_PROPERTIESENTRY.containing_type = _LANECONFIGUREREQUEST
_LANECONFIGUREREQUEST.fields_by_name['properties'].message_type = _LANECONFIGUREREQUEST_PROPERTIESENTRY
_LANECONFIGURERESPONSE_MD5MAPENTRY.containing_type = _LANECONFIGURERESPONSE
_LANECONFIGURERESPONSE.fields_by_name['md5_map'].message_type = _LANECONFIGURERESPONSE_MD5MAPENTRY
DESCRIPTOR.message_types_by_name['LaneErrorResponse'] = _LANEERRORRESPONSE
DESCRIPTOR.message_types_by_name['LaneConfigureRequest'] = _LANECONFIGUREREQUEST
DESCRIPTOR.message_types_by_name['LaneConfigureResponse'] = _LANECONFIGURERESPONSE
DESCRIPTOR.message_types_by_name['ProcessScanDataRequest'] = _PROCESSSCANDATAREQUEST
DESCRIPTOR.message_types_by_name['ProcessScanDataResponse'] = _PROCESSSCANDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaneErrorResponse = _reflection.GeneratedProtocolMessageType('LaneErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANEERRORRESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.LaneErrorResponse)
  })
_sym_db.RegisterMessage(LaneErrorResponse)

LaneConfigureRequest = _reflection.GeneratedProtocolMessageType('LaneConfigureRequest', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _LANECONFIGUREREQUEST_PROPERTIESENTRY,
    '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
    # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.LaneConfigureRequest.PropertiesEntry)
    })
  ,
  'DESCRIPTOR' : _LANECONFIGUREREQUEST,
  '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.LaneConfigureRequest)
  })
_sym_db.RegisterMessage(LaneConfigureRequest)
_sym_db.RegisterMessage(LaneConfigureRequest.PropertiesEntry)

LaneConfigureResponse = _reflection.GeneratedProtocolMessageType('LaneConfigureResponse', (_message.Message,), {

  'Md5MapEntry' : _reflection.GeneratedProtocolMessageType('Md5MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _LANECONFIGURERESPONSE_MD5MAPENTRY,
    '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
    # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.LaneConfigureResponse.Md5MapEntry)
    })
  ,
  'DESCRIPTOR' : _LANECONFIGURERESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.LaneConfigureResponse)
  })
_sym_db.RegisterMessage(LaneConfigureResponse)
_sym_db.RegisterMessage(LaneConfigureResponse.Md5MapEntry)

ProcessScanDataRequest = _reflection.GeneratedProtocolMessageType('ProcessScanDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSSCANDATAREQUEST,
  '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.ProcessScanDataRequest)
  })
_sym_db.RegisterMessage(ProcessScanDataRequest)

ProcessScanDataResponse = _reflection.GeneratedProtocolMessageType('ProcessScanDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSSCANDATARESPONSE,
  '__module__' : 'gov.llnl.ernie.raven.proto.lane_pb2'
  # @@protoc_insertion_point(class_scope:gov.llnl.ernie.raven.ProcessScanDataResponse)
  })
_sym_db.RegisterMessage(ProcessScanDataResponse)


DESCRIPTOR._options = None
_LANECONFIGUREREQUEST_PROPERTIESENTRY._options = None
_LANECONFIGURERESPONSE_MD5MAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
