/*
 * The contents of this file are subject to the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one
 * at http://mozilla.org/MPL/2.0/.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the License.
 *
 * Copyright (c) 2023 Botts Innovative Research, Inc. All Rights Reserved.
 */

package com.botts.impl.sensor.kromek.d5.enums;

public enum KromekSerialNuclideIdType {
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Am_241,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Ba_133,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Cs_137,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Co_57,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Co_60,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_EU_152,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_F_18,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Ga_67,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_I_123,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_I_131,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Ir_192,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Lu_177,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Lu_177m,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Mo_99,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Np_237,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Pu_239,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_WGPu,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_RGPu,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_K_40,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Ra_226,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Na_22,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Tc_99m,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Tl_201,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Th_232,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_U_235,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_U_238,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_DU,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_HEU,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_Y_88,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_MAX,
    KROMEK_SERIAL_NUCLIDE_ID_TYPE_UNKNOWN
}
