/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class D3SpectrumChartOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected D3SpectrumChartOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(D3SpectrumChartOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(D3SpectrumChartOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_D3SpectrumChartOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public D3SpectrumChartOptions() {
    this(SpecUtilsSwigJNI.new_D3SpectrumChartOptions__SWIG_0(), true);
  }

  public D3SpectrumChartOptions(String title, String xAxisTitle, String yAxisTitle, String dataTitle, boolean useLogYAxis, boolean showVerticalGridLines, boolean showHorizontalGridLines, boolean legendEnabled, boolean compactXAxis, boolean showPeakUserLabels, boolean showPeakEnergyLabels, boolean showPeakNuclideLabels, boolean showPeakNuclideEnergyLabels, boolean showEscapePeakMarker, boolean showComptonPeakMarker, boolean showComptonEdgeMarker, boolean showSumPeakMarker, boolean backgroundSubtract, float xMin, float xMax, SWIGTYPE_p_std__mapT_std__string_std__string_t refernce_lines_json) {
    this(SpecUtilsSwigJNI.new_D3SpectrumChartOptions__SWIG_1(title, xAxisTitle, yAxisTitle, dataTitle, useLogYAxis, showVerticalGridLines, showHorizontalGridLines, legendEnabled, compactXAxis, showPeakUserLabels, showPeakEnergyLabels, showPeakNuclideLabels, showPeakNuclideEnergyLabels, showEscapePeakMarker, showComptonPeakMarker, showComptonEdgeMarker, showSumPeakMarker, backgroundSubtract, xMin, xMax, SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(refernce_lines_json)), true);
  }

  public void setM_title(String value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_title_set(swigCPtr, this, value);
  }

  public String getM_title() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_title_get(swigCPtr, this);
  }

  public void setM_xAxisTitle(String value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_xAxisTitle_set(swigCPtr, this, value);
  }

  public String getM_xAxisTitle() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_xAxisTitle_get(swigCPtr, this);
  }

  public void setM_yAxisTitle(String value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_yAxisTitle_set(swigCPtr, this, value);
  }

  public String getM_yAxisTitle() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_yAxisTitle_get(swigCPtr, this);
  }

  public void setM_dataTitle(String value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_dataTitle_set(swigCPtr, this, value);
  }

  public String getM_dataTitle() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_dataTitle_get(swigCPtr, this);
  }

  public void setM_useLogYAxis(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_useLogYAxis_set(swigCPtr, this, value);
  }

  public boolean getM_useLogYAxis() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_useLogYAxis_get(swigCPtr, this);
  }

  public void setM_showVerticalGridLines(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showVerticalGridLines_set(swigCPtr, this, value);
  }

  public boolean getM_showVerticalGridLines() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showVerticalGridLines_get(swigCPtr, this);
  }

  public void setM_showHorizontalGridLines(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showHorizontalGridLines_set(swigCPtr, this, value);
  }

  public boolean getM_showHorizontalGridLines() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showHorizontalGridLines_get(swigCPtr, this);
  }

  public void setM_legendEnabled(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_legendEnabled_set(swigCPtr, this, value);
  }

  public boolean getM_legendEnabled() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_legendEnabled_get(swigCPtr, this);
  }

  public void setM_compactXAxis(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_compactXAxis_set(swigCPtr, this, value);
  }

  public boolean getM_compactXAxis() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_compactXAxis_get(swigCPtr, this);
  }

  public void setM_showPeakUserLabels(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakUserLabels_set(swigCPtr, this, value);
  }

  public boolean getM_showPeakUserLabels() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakUserLabels_get(swigCPtr, this);
  }

  public void setM_showPeakEnergyLabels(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakEnergyLabels_set(swigCPtr, this, value);
  }

  public boolean getM_showPeakEnergyLabels() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakEnergyLabels_get(swigCPtr, this);
  }

  public void setM_showPeakNuclideLabels(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakNuclideLabels_set(swigCPtr, this, value);
  }

  public boolean getM_showPeakNuclideLabels() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakNuclideLabels_get(swigCPtr, this);
  }

  public void setM_showPeakNuclideEnergyLabels(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakNuclideEnergyLabels_set(swigCPtr, this, value);
  }

  public boolean getM_showPeakNuclideEnergyLabels() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showPeakNuclideEnergyLabels_get(swigCPtr, this);
  }

  public void setM_showEscapePeakMarker(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showEscapePeakMarker_set(swigCPtr, this, value);
  }

  public boolean getM_showEscapePeakMarker() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showEscapePeakMarker_get(swigCPtr, this);
  }

  public void setM_showComptonPeakMarker(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showComptonPeakMarker_set(swigCPtr, this, value);
  }

  public boolean getM_showComptonPeakMarker() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showComptonPeakMarker_get(swigCPtr, this);
  }

  public void setM_showComptonEdgeMarker(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showComptonEdgeMarker_set(swigCPtr, this, value);
  }

  public boolean getM_showComptonEdgeMarker() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showComptonEdgeMarker_get(swigCPtr, this);
  }

  public void setM_showSumPeakMarker(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showSumPeakMarker_set(swigCPtr, this, value);
  }

  public boolean getM_showSumPeakMarker() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_showSumPeakMarker_get(swigCPtr, this);
  }

  public void setM_backgroundSubtract(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_backgroundSubtract_set(swigCPtr, this, value);
  }

  public boolean getM_backgroundSubtract() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_backgroundSubtract_get(swigCPtr, this);
  }

  public void setM_allowDragRoiExtent(boolean value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_allowDragRoiExtent_set(swigCPtr, this, value);
  }

  public boolean getM_allowDragRoiExtent() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_allowDragRoiExtent_get(swigCPtr, this);
  }

  public void setM_xMin(float value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_xMin_set(swigCPtr, this, value);
  }

  public float getM_xMin() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_xMin_get(swigCPtr, this);
  }

  public void setM_xMax(float value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_xMax_set(swigCPtr, this, value);
  }

  public float getM_xMax() {
    return SpecUtilsSwigJNI.D3SpectrumChartOptions_m_xMax_get(swigCPtr, this);
  }

  public void setM_reference_lines_json(SWIGTYPE_p_std__mapT_std__string_std__string_t value) {
    SpecUtilsSwigJNI.D3SpectrumChartOptions_m_reference_lines_json_set(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t getM_reference_lines_json() {
    long cPtr = SpecUtilsSwigJNI.D3SpectrumChartOptions_m_reference_lines_json_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_std__string_std__string_t(cPtr, false);
  }

}
