/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class D3SpectrumOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected D3SpectrumOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(D3SpectrumOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(D3SpectrumOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_D3SpectrumOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public D3SpectrumOptions() {
    this(SpecUtilsSwigJNI.new_D3SpectrumOptions(), true);
  }

  public void setPeaks_json(String value) {
    SpecUtilsSwigJNI.D3SpectrumOptions_peaks_json_set(swigCPtr, this, value);
  }

  public String getPeaks_json() {
    return SpecUtilsSwigJNI.D3SpectrumOptions_peaks_json_get(swigCPtr, this);
  }

  public void setLine_color(String value) {
    SpecUtilsSwigJNI.D3SpectrumOptions_line_color_set(swigCPtr, this, value);
  }

  public String getLine_color() {
    return SpecUtilsSwigJNI.D3SpectrumOptions_line_color_get(swigCPtr, this);
  }

  public void setPeak_color(String value) {
    SpecUtilsSwigJNI.D3SpectrumOptions_peak_color_set(swigCPtr, this, value);
  }

  public String getPeak_color() {
    return SpecUtilsSwigJNI.D3SpectrumOptions_peak_color_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    SpecUtilsSwigJNI.D3SpectrumOptions_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return SpecUtilsSwigJNI.D3SpectrumOptions_title_get(swigCPtr, this);
  }

  public void setDisplay_scale_factor(double value) {
    SpecUtilsSwigJNI.D3SpectrumOptions_display_scale_factor_set(swigCPtr, this, value);
  }

  public double getDisplay_scale_factor() {
    return SpecUtilsSwigJNI.D3SpectrumOptions_display_scale_factor_get(swigCPtr, this);
  }

  public void setSpectrum_type(SpectrumType value) {
    SpecUtilsSwigJNI.D3SpectrumOptions_spectrum_type_set(swigCPtr, this, value.swigValue());
  }

  public SpectrumType getSpectrum_type() {
    return SpectrumType.swigToEnum(SpecUtilsSwigJNI.D3SpectrumOptions_spectrum_type_get(swigCPtr, this));
  }

}
