/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class DetectorAnalysis {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DetectorAnalysis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DetectorAnalysis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DetectorAnalysis obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_DetectorAnalysis(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRemarks_(StringVector value) {
    SpecUtilsSwigJNI.DetectorAnalysis_remarks__set(swigCPtr, this, StringVector.getCPtr(value), value);
  }

  public StringVector getRemarks_() {
    long cPtr = SpecUtilsSwigJNI.DetectorAnalysis_remarks__get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringVector(cPtr, false);
  }

  public void setAlgorithm_name_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysis_algorithm_name__set(swigCPtr, this, value);
  }

  public String getAlgorithm_name_() {
    return SpecUtilsSwigJNI.DetectorAnalysis_algorithm_name__get(swigCPtr, this);
  }

  public void setAlgorithm_component_versions_(SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t value) {
    SpecUtilsSwigJNI.DetectorAnalysis_algorithm_component_versions__set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t getAlgorithm_component_versions_() {
    long cPtr = SpecUtilsSwigJNI.DetectorAnalysis_algorithm_component_versions__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t(cPtr, false);
  }

  public void setAlgorithm_creator_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysis_algorithm_creator__set(swigCPtr, this, value);
  }

  public String getAlgorithm_creator_() {
    return SpecUtilsSwigJNI.DetectorAnalysis_algorithm_creator__get(swigCPtr, this);
  }

  public void setAlgorithm_description_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysis_algorithm_description__set(swigCPtr, this, value);
  }

  public String getAlgorithm_description_() {
    return SpecUtilsSwigJNI.DetectorAnalysis_algorithm_description__get(swigCPtr, this);
  }

  public void setAnalysis_start_time_(SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t value) {
    SpecUtilsSwigJNI.DetectorAnalysis_analysis_start_time__set(swigCPtr, this, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t getAnalysis_start_time_() {
    return new SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t(SpecUtilsSwigJNI.DetectorAnalysis_analysis_start_time__get(swigCPtr, this), true);
  }

  public void setAnalysis_computation_duration_(float value) {
    SpecUtilsSwigJNI.DetectorAnalysis_analysis_computation_duration__set(swigCPtr, this, value);
  }

  public float getAnalysis_computation_duration_() {
    return SpecUtilsSwigJNI.DetectorAnalysis_analysis_computation_duration__get(swigCPtr, this);
  }

  public void setAlgorithm_result_description_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysis_algorithm_result_description__set(swigCPtr, this, value);
  }

  public String getAlgorithm_result_description_() {
    return SpecUtilsSwigJNI.DetectorAnalysis_algorithm_result_description__get(swigCPtr, this);
  }

  public void setResults_(SWIGTYPE_p_std__vectorT_SpecUtils__DetectorAnalysisResult_t value) {
    SpecUtilsSwigJNI.DetectorAnalysis_results__set(swigCPtr, this, SWIGTYPE_p_std__vectorT_SpecUtils__DetectorAnalysisResult_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_SpecUtils__DetectorAnalysisResult_t getResults_() {
    long cPtr = SpecUtilsSwigJNI.DetectorAnalysis_results__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_SpecUtils__DetectorAnalysisResult_t(cPtr, false);
  }

  public DetectorAnalysis() {
    this(SpecUtilsSwigJNI.new_DetectorAnalysis(), true);
  }

  public void reset() {
    SpecUtilsSwigJNI.DetectorAnalysis_reset(swigCPtr, this);
  }

  public boolean is_empty() {
    return SpecUtilsSwigJNI.DetectorAnalysis_is_empty(swigCPtr, this);
  }

}
