/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class DetectorAnalysisResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DetectorAnalysisResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DetectorAnalysisResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DetectorAnalysisResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_DetectorAnalysisResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRemark_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_remark__set(swigCPtr, this, value);
  }

  public String getRemark_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_remark__get(swigCPtr, this);
  }

  public void setNuclide_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_nuclide__set(swigCPtr, this, value);
  }

  public String getNuclide_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_nuclide__get(swigCPtr, this);
  }

  public void setActivity_(float value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_activity__set(swigCPtr, this, value);
  }

  public float getActivity_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_activity__get(swigCPtr, this);
  }

  public void setNuclide_type_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_nuclide_type__set(swigCPtr, this, value);
  }

  public String getNuclide_type_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_nuclide_type__get(swigCPtr, this);
  }

  public void setId_confidence_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_id_confidence__set(swigCPtr, this, value);
  }

  public String getId_confidence_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_id_confidence__get(swigCPtr, this);
  }

  public void setDistance_(float value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_distance__set(swigCPtr, this, value);
  }

  public float getDistance_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_distance__get(swigCPtr, this);
  }

  public void setDose_rate_(float value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_dose_rate__set(swigCPtr, this, value);
  }

  public float getDose_rate_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_dose_rate__get(swigCPtr, this);
  }

  public void setReal_time_(float value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_real_time__set(swigCPtr, this, value);
  }

  public float getReal_time_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_real_time__get(swigCPtr, this);
  }

  public void setDetector_(String value) {
    SpecUtilsSwigJNI.DetectorAnalysisResult_detector__set(swigCPtr, this, value);
  }

  public String getDetector_() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_detector__get(swigCPtr, this);
  }

  public DetectorAnalysisResult() {
    this(SpecUtilsSwigJNI.new_DetectorAnalysisResult(), true);
  }

  public void reset() {
    SpecUtilsSwigJNI.DetectorAnalysisResult_reset(swigCPtr, this);
  }

  public boolean isEmpty() {
    return SpecUtilsSwigJNI.DetectorAnalysisResult_isEmpty(swigCPtr, this);
  }

}
