/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class DetectorType {
  public final static DetectorType Exploranium = new DetectorType("Exploranium");
  public final static DetectorType IdentiFinder = new DetectorType("IdentiFinder");
  public final static DetectorType IdentiFinderNG = new DetectorType("IdentiFinderNG");
  public final static DetectorType IdentiFinderLaBr3 = new DetectorType("IdentiFinderLaBr3");
  public final static DetectorType IdentiFinderTungsten = new DetectorType("IdentiFinderTungsten");
  public final static DetectorType IdentiFinderR425NaI = new DetectorType("IdentiFinderR425NaI");
  public final static DetectorType IdentiFinderR425LaBr = new DetectorType("IdentiFinderR425LaBr");
  public final static DetectorType IdentiFinderR500NaI = new DetectorType("IdentiFinderR500NaI");
  public final static DetectorType IdentiFinderR500LaBr = new DetectorType("IdentiFinderR500LaBr");
  public final static DetectorType IdentiFinderUnknown = new DetectorType("IdentiFinderUnknown");
  public final static DetectorType DetectiveUnknown = new DetectorType("DetectiveUnknown");
  public final static DetectorType DetectiveEx = new DetectorType("DetectiveEx");
  public final static DetectorType DetectiveEx100 = new DetectorType("DetectiveEx100");
  public final static DetectorType DetectiveEx200 = new DetectorType("DetectiveEx200");
  public final static DetectorType DetectiveX = new DetectorType("DetectiveX");
  public final static DetectorType SAIC8 = new DetectorType("SAIC8");
  public final static DetectorType Falcon5000 = new DetectorType("Falcon5000");
  public final static DetectorType MicroDetective = new DetectorType("MicroDetective");
  public final static DetectorType MicroRaider = new DetectorType("MicroRaider");
  public final static DetectorType RadiaCode = new DetectorType("RadiaCode");
  public final static DetectorType Interceptor = new DetectorType("Interceptor");
  public final static DetectorType RadHunterNaI = new DetectorType("RadHunterNaI");
  public final static DetectorType RadHunterLaBr3 = new DetectorType("RadHunterLaBr3");
  public final static DetectorType Rsi701 = new DetectorType("Rsi701");
  public final static DetectorType Rsi705 = new DetectorType("Rsi705");
  public final static DetectorType AvidRsi = new DetectorType("AvidRsi");
  public final static DetectorType OrtecRadEagleNai = new DetectorType("OrtecRadEagleNai");
  public final static DetectorType OrtecRadEagleCeBr2Inch = new DetectorType("OrtecRadEagleCeBr2Inch");
  public final static DetectorType OrtecRadEagleCeBr3Inch = new DetectorType("OrtecRadEagleCeBr3Inch");
  public final static DetectorType OrtecRadEagleLaBr = new DetectorType("OrtecRadEagleLaBr");
  public final static DetectorType Sam940LaBr3 = new DetectorType("Sam940LaBr3");
  public final static DetectorType Sam940 = new DetectorType("Sam940");
  public final static DetectorType Sam945 = new DetectorType("Sam945");
  public final static DetectorType Srpm210 = new DetectorType("Srpm210");
  public final static DetectorType RIIDEyeNaI = new DetectorType("RIIDEyeNaI");
  public final static DetectorType RIIDEyeLaBr = new DetectorType("RIIDEyeLaBr");
  public final static DetectorType RadSeekerNaI = new DetectorType("RadSeekerNaI");
  public final static DetectorType RadSeekerLaBr = new DetectorType("RadSeekerLaBr");
  public final static DetectorType VerifinderNaI = new DetectorType("VerifinderNaI");
  public final static DetectorType VerifinderLaBr = new DetectorType("VerifinderLaBr");
  public final static DetectorType KromekD3S = new DetectorType("KromekD3S");
  public final static DetectorType Fulcrum = new DetectorType("Fulcrum");
  public final static DetectorType Fulcrum40h = new DetectorType("Fulcrum40h");
  public final static DetectorType Sam950 = new DetectorType("Sam950");
  public final static DetectorType Unknown = new DetectorType("Unknown");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DetectorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DetectorType.class + " with value " + swigValue);
  }

  private DetectorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DetectorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DetectorType(String swigName, DetectorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DetectorType[] swigValues = { Exploranium, IdentiFinder, IdentiFinderNG, IdentiFinderLaBr3, IdentiFinderTungsten, IdentiFinderR425NaI, IdentiFinderR425LaBr, IdentiFinderR500NaI, IdentiFinderR500LaBr, IdentiFinderUnknown, DetectiveUnknown, DetectiveEx, DetectiveEx100, DetectiveEx200, DetectiveX, SAIC8, Falcon5000, MicroDetective, MicroRaider, RadiaCode, Interceptor, RadHunterNaI, RadHunterLaBr3, Rsi701, Rsi705, AvidRsi, OrtecRadEagleNai, OrtecRadEagleCeBr2Inch, OrtecRadEagleCeBr3Inch, OrtecRadEagleLaBr, Sam940LaBr3, Sam940, Sam945, Srpm210, RIIDEyeNaI, RIIDEyeLaBr, RadSeekerNaI, RadSeekerLaBr, VerifinderNaI, VerifinderLaBr, KromekD3S, Fulcrum, Fulcrum40h, Sam950, Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

