/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class EnergyCalibration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EnergyCalibration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnergyCalibration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EnergyCalibration obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_EnergyCalibration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EnergyCalType type() {
    return EnergyCalType.swigToEnum(SpecUtilsSwigJNI.EnergyCalibration_type(swigCPtr, this));
  }

  public boolean valid() {
    return SpecUtilsSwigJNI.EnergyCalibration_valid(swigCPtr, this);
  }

  public FloatVector coefficients() {
    return new FloatVector(SpecUtilsSwigJNI.EnergyCalibration_coefficients(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs() {
    return new SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t(SpecUtilsSwigJNI.EnergyCalibration_deviation_pairs(swigCPtr, this), false);
  }

  public FloatVector channel_energies() {
    long cPtr = SpecUtilsSwigJNI.EnergyCalibration_channel_energies(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public long num_channels() {
    return SpecUtilsSwigJNI.EnergyCalibration_num_channels(swigCPtr, this);
  }

  public EnergyCalibration() {
    this(SpecUtilsSwigJNI.new_EnergyCalibration(), true);
  }

  public void set_polynomial(long num_channels, FloatVector coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    SpecUtilsSwigJNI.EnergyCalibration_set_polynomial(swigCPtr, this, num_channels, FloatVector.getCPtr(coeffs), coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
  }

  public void set_default_polynomial(long num_channels, FloatVector coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    SpecUtilsSwigJNI.EnergyCalibration_set_default_polynomial(swigCPtr, this, num_channels, FloatVector.getCPtr(coeffs), coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
  }

  public void set_full_range_fraction(long num_channels, FloatVector coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    SpecUtilsSwigJNI.EnergyCalibration_set_full_range_fraction(swigCPtr, this, num_channels, FloatVector.getCPtr(coeffs), coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
  }

  public void set_lower_channel_energy(long num_channels, FloatVector channel_energies) {
    SpecUtilsSwigJNI.EnergyCalibration_set_lower_channel_energy__SWIG_0(swigCPtr, this, num_channels, FloatVector.getCPtr(channel_energies), channel_energies);
  }

  public long memmorysize() {
    return SpecUtilsSwigJNI.EnergyCalibration_memmorysize(swigCPtr, this);
  }

  public double channel_for_energy(double energy) {
    return SpecUtilsSwigJNI.EnergyCalibration_channel_for_energy(swigCPtr, this, energy);
  }

  public double energy_for_channel(double channel) {
    return SpecUtilsSwigJNI.EnergyCalibration_energy_for_channel(swigCPtr, this, channel);
  }

  public float lower_energy() {
    return SpecUtilsSwigJNI.EnergyCalibration_lower_energy(swigCPtr, this);
  }

  public float upper_energy() {
    return SpecUtilsSwigJNI.EnergyCalibration_upper_energy(swigCPtr, this);
  }

  public static long getSm_min_channels() {
    return SpecUtilsSwigJNI.EnergyCalibration_sm_min_channels_get();
  }

  public static long getSm_max_channels() {
    return SpecUtilsSwigJNI.EnergyCalibration_sm_max_channels_get();
  }

  public static float getSm_polynomial_offset_limit() {
    return SpecUtilsSwigJNI.EnergyCalibration_sm_polynomial_offset_limit_get();
  }

}
