/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class EnergyCalType {
  public final static EnergyCalType Polynomial = new EnergyCalType("Polynomial");
  public final static EnergyCalType FullRangeFraction = new EnergyCalType("FullRangeFraction");
  public final static EnergyCalType LowerChannelEdge = new EnergyCalType("LowerChannelEdge");
  public final static EnergyCalType UnspecifiedUsingDefaultPolynomial = new EnergyCalType("UnspecifiedUsingDefaultPolynomial");
  public final static EnergyCalType InvalidEquationType = new EnergyCalType("InvalidEquationType");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EnergyCalType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EnergyCalType.class + " with value " + swigValue);
  }

  private EnergyCalType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EnergyCalType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EnergyCalType(String swigName, EnergyCalType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EnergyCalType[] swigValues = { Polynomial, FullRangeFraction, LowerChannelEdge, UnspecifiedUsingDefaultPolynomial, InvalidEquationType };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

