/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class FloatVector extends java.util.AbstractList<Float> implements java.util.RandomAccess {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FloatVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_FloatVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public FloatVector(float[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (float element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public FloatVector(Iterable<Float> initialElements) {
    this();
    for (float element : initialElements) {
      doAdd(element);
    }
  }

  public Float get(int index) {
    return doGet(index);
  }

  public Float set(int index, Float e) {
    return doSet(index, e);
  }

  public boolean add(Float e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Float e) {
    modCount++;
    doAdd(index, e);
  }

  public Float remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public FloatVector() {
    this(SpecUtilsSwigJNI.new_FloatVector__SWIG_0(), true);
  }

  public FloatVector(FloatVector other) {
    this(SpecUtilsSwigJNI.new_FloatVector__SWIG_1(FloatVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return SpecUtilsSwigJNI.FloatVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SpecUtilsSwigJNI.FloatVector_clear(swigCPtr, this);
  }

  public FloatVector(int count, float value) {
    this(SpecUtilsSwigJNI.new_FloatVector__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return SpecUtilsSwigJNI.FloatVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    SpecUtilsSwigJNI.FloatVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return SpecUtilsSwigJNI.FloatVector_doSize(swigCPtr, this);
  }

  private void doAdd(float x) {
    SpecUtilsSwigJNI.FloatVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, float x) {
    SpecUtilsSwigJNI.FloatVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private float doRemove(int index) {
    return SpecUtilsSwigJNI.FloatVector_doRemove(swigCPtr, this, index);
  }

  private float doGet(int index) {
    return SpecUtilsSwigJNI.FloatVector_doGet(swigCPtr, this, index);
  }

  private float doSet(int index, float val) {
    return SpecUtilsSwigJNI.FloatVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SpecUtilsSwigJNI.FloatVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
