/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class Measurement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Measurement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Measurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_Measurement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Measurement() {
    this(SpecUtilsSwigJNI.new_Measurement(), true);
  }

  public Measurement operatorEqual(Measurement rhs) {
    return new Measurement(SpecUtilsSwigJNI.Measurement_operatorEqual(swigCPtr, this, Measurement.getCPtr(rhs), rhs), true);
  }

  public long memmorysize() {
    return SpecUtilsSwigJNI.Measurement_memmorysize(swigCPtr, this);
  }

  public float live_time() {
    return SpecUtilsSwigJNI.Measurement_live_time(swigCPtr, this);
  }

  public float real_time() {
    return SpecUtilsSwigJNI.Measurement_real_time(swigCPtr, this);
  }

  public boolean contained_neutron() {
    return SpecUtilsSwigJNI.Measurement_contained_neutron(swigCPtr, this);
  }

  public int sample_number() {
    return SpecUtilsSwigJNI.Measurement_sample_number(swigCPtr, this);
  }

  public String title() {
    return SpecUtilsSwigJNI.Measurement_title(swigCPtr, this);
  }

  public OccupancyStatus occupied() {
    return OccupancyStatus.swigToEnum(SpecUtilsSwigJNI.Measurement_occupied(swigCPtr, this));
  }

  public double gamma_count_sum() {
    return SpecUtilsSwigJNI.Measurement_gamma_count_sum(swigCPtr, this);
  }

  public float neutron_live_time() {
    return SpecUtilsSwigJNI.Measurement_neutron_live_time(swigCPtr, this);
  }

  public double neutron_counts_sum() {
    return SpecUtilsSwigJNI.Measurement_neutron_counts_sum(swigCPtr, this);
  }

  public float speed() {
    return SpecUtilsSwigJNI.Measurement_speed(swigCPtr, this);
  }

  public float dx() {
    return SpecUtilsSwigJNI.Measurement_dx(swigCPtr, this);
  }

  public float dy() {
    return SpecUtilsSwigJNI.Measurement_dy(swigCPtr, this);
  }

  public double latitude() {
    return SpecUtilsSwigJNI.Measurement_latitude(swigCPtr, this);
  }

  public double longitude() {
    return SpecUtilsSwigJNI.Measurement_longitude(swigCPtr, this);
  }

  public boolean has_gps_info() {
    return SpecUtilsSwigJNI.Measurement_has_gps_info(swigCPtr, this);
  }

  public float dose_rate() {
    return SpecUtilsSwigJNI.Measurement_dose_rate(swigCPtr, this);
  }

  public float exposure_rate() {
    return SpecUtilsSwigJNI.Measurement_exposure_rate(swigCPtr, this);
  }

  public SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t position_time() {
    return new SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t(SpecUtilsSwigJNI.Measurement_position_time(swigCPtr, this), true);
  }

  public String detector_name() {
    return SpecUtilsSwigJNI.Measurement_detector_name(swigCPtr, this);
  }

  public int detector_number() {
    return SpecUtilsSwigJNI.Measurement_detector_number(swigCPtr, this);
  }

  public String detector_type() {
    return SpecUtilsSwigJNI.Measurement_detector_type(swigCPtr, this);
  }

  public QualityStatus quality_status() {
    return QualityStatus.swigToEnum(SpecUtilsSwigJNI.Measurement_quality_status(swigCPtr, this));
  }

  public SourceType source_type() {
    return SourceType.swigToEnum(SpecUtilsSwigJNI.Measurement_source_type(swigCPtr, this));
  }

  public StringVector remarks() {
    return new StringVector(SpecUtilsSwigJNI.Measurement_remarks(swigCPtr, this), false);
  }

  public StringVector parse_warnings() {
    return new StringVector(SpecUtilsSwigJNI.Measurement_parse_warnings(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t start_time() {
    return new SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t(SpecUtilsSwigJNI.Measurement_start_time(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t start_time_copy() {
    return new SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t(SpecUtilsSwigJNI.Measurement_start_time_copy(swigCPtr, this), true);
  }

  public EnergyCalType energy_calibration_model() {
    return EnergyCalType.swigToEnum(SpecUtilsSwigJNI.Measurement_energy_calibration_model(swigCPtr, this));
  }

  public FloatVector calibration_coeffs() {
    return new FloatVector(SpecUtilsSwigJNI.Measurement_calibration_coeffs(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs() {
    return new SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t(SpecUtilsSwigJNI.Measurement_deviation_pairs(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t energy_calibration() {
    return new SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t(SpecUtilsSwigJNI.Measurement_energy_calibration(swigCPtr, this), true);
  }

  public FloatVector channel_energies() {
    long cPtr = SpecUtilsSwigJNI.Measurement_channel_energies(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public FloatVector gamma_counts() {
    long cPtr = SpecUtilsSwigJNI.Measurement_gamma_counts(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public FloatVector neutron_counts() {
    return new FloatVector(SpecUtilsSwigJNI.Measurement_neutron_counts(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_SpecUtils__LocationState_const_t location_state() {
    return new SWIGTYPE_p_std__shared_ptrT_SpecUtils__LocationState_const_t(SpecUtilsSwigJNI.Measurement_location_state(swigCPtr, this), false);
  }

  public void set_title(String title) {
    SpecUtilsSwigJNI.Measurement_set_title(swigCPtr, this, title);
  }

  public void set_start_time(SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t timestamp) {
    SpecUtilsSwigJNI.Measurement_set_start_time(swigCPtr, this, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t.getCPtr(timestamp));
  }

  public void set_remarks(StringVector remarks) {
    SpecUtilsSwigJNI.Measurement_set_remarks(swigCPtr, this, StringVector.getCPtr(remarks), remarks);
  }

  public void set_parse_warnings(StringVector warnings) {
    SpecUtilsSwigJNI.Measurement_set_parse_warnings(swigCPtr, this, StringVector.getCPtr(warnings), warnings);
  }

  public void set_source_type(SourceType type) {
    SpecUtilsSwigJNI.Measurement_set_source_type(swigCPtr, this, type.swigValue());
  }

  public void set_position(double longitude, double latitude, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t pos_time) {
    SpecUtilsSwigJNI.Measurement_set_position(swigCPtr, this, longitude, latitude, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t.getCPtr(pos_time));
  }

  public void set_sample_number(int samplenum) {
    SpecUtilsSwigJNI.Measurement_set_sample_number(swigCPtr, this, samplenum);
  }

  public void set_occupancy_status(OccupancyStatus status) {
    SpecUtilsSwigJNI.Measurement_set_occupancy_status(swigCPtr, this, status.swigValue());
  }

  public void set_detector_name(String name) {
    SpecUtilsSwigJNI.Measurement_set_detector_name(swigCPtr, this, name);
  }

  public void set_detector_number(int detnum) {
    SpecUtilsSwigJNI.Measurement_set_detector_number(swigCPtr, this, detnum);
  }

  public void set_gamma_counts(FloatVector counts, float livetime, float realtime) {
    SpecUtilsSwigJNI.Measurement_set_gamma_counts(swigCPtr, this, FloatVector.getCPtr(counts), counts, livetime, realtime);
  }

  public void set_neutron_counts(FloatVector counts, float neutron_live_time) {
    SpecUtilsSwigJNI.Measurement_set_neutron_counts(swigCPtr, this, FloatVector.getCPtr(counts), counts, neutron_live_time);
  }

  public long num_gamma_channels() {
    return SpecUtilsSwigJNI.Measurement_num_gamma_channels(swigCPtr, this);
  }

  public long find_gamma_channel(float energy) {
    return SpecUtilsSwigJNI.Measurement_find_gamma_channel(swigCPtr, this, energy);
  }

  public float gamma_channel_content(long channel) {
    return SpecUtilsSwigJNI.Measurement_gamma_channel_content(swigCPtr, this, channel);
  }

  public float gamma_channel_lower(long channel) {
    return SpecUtilsSwigJNI.Measurement_gamma_channel_lower(swigCPtr, this, channel);
  }

  public float gamma_channel_center(long channel) {
    return SpecUtilsSwigJNI.Measurement_gamma_channel_center(swigCPtr, this, channel);
  }

  public float gamma_channel_upper(long channel) {
    return SpecUtilsSwigJNI.Measurement_gamma_channel_upper(swigCPtr, this, channel);
  }

  public float gamma_channel_width(long channel) {
    return SpecUtilsSwigJNI.Measurement_gamma_channel_width(swigCPtr, this, channel);
  }

  public double gamma_integral(float lower_energy, float upper_energy) {
    return SpecUtilsSwigJNI.Measurement_gamma_integral(swigCPtr, this, lower_energy, upper_energy);
  }

  public double gamma_channels_sum(long startbin, long endbin) {
    return SpecUtilsSwigJNI.Measurement_gamma_channels_sum(swigCPtr, this, startbin, endbin);
  }

  public FloatVector gamma_channel_energies() {
    long cPtr = SpecUtilsSwigJNI.Measurement_gamma_channel_energies(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public FloatVector gamma_channel_contents() {
    long cPtr = SpecUtilsSwigJNI.Measurement_gamma_channel_contents(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public float gamma_energy_min() {
    return SpecUtilsSwigJNI.Measurement_gamma_energy_min(swigCPtr, this);
  }

  public float gamma_energy_max() {
    return SpecUtilsSwigJNI.Measurement_gamma_energy_max(swigCPtr, this);
  }

  public SWIGTYPE_p_uint32_t derived_data_properties() {
    return new SWIGTYPE_p_uint32_t(SpecUtilsSwigJNI.Measurement_derived_data_properties(swigCPtr, this), true);
  }

  public boolean write_2006_N42_xml(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.Measurement_write_2006_N42_xml(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public boolean write_csv(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.Measurement_write_csv(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public boolean write_txt(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.Measurement_write_txt(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public void reset() {
    SpecUtilsSwigJNI.Measurement_reset(swigCPtr, this);
  }

  public void combine_gamma_channels(long nchannel) {
    SpecUtilsSwigJNI.Measurement_combine_gamma_channels(swigCPtr, this, nchannel);
  }

  public void truncate_gamma_channels(long keep_first_channel, long keep_last_channel, boolean keep_under_over_flow) {
    SpecUtilsSwigJNI.Measurement_truncate_gamma_channels(swigCPtr, this, keep_first_channel, keep_last_channel, keep_under_over_flow);
  }

  public void rebin(SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal) {
    SpecUtilsSwigJNI.Measurement_rebin(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal));
  }

  public void set_energy_calibration(SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal) {
    SpecUtilsSwigJNI.Measurement_set_energy_calibration(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal));
  }

  public void set_info_from_2006_N42_spectrum_node(SWIGTYPE_p_rapidxml__xml_nodeT_char_t spectrum) {
    SpecUtilsSwigJNI.Measurement_set_info_from_2006_N42_spectrum_node(swigCPtr, this, SWIGTYPE_p_rapidxml__xml_nodeT_char_t.getCPtr(spectrum));
  }

  public final static class DerivedDataProperties {
    public final static Measurement.DerivedDataProperties IsDerived = new Measurement.DerivedDataProperties("IsDerived", SpecUtilsSwigJNI.Measurement_DerivedDataProperties_IsDerived_get());
    public final static Measurement.DerivedDataProperties ItemOfInterestSum = new Measurement.DerivedDataProperties("ItemOfInterestSum", SpecUtilsSwigJNI.Measurement_DerivedDataProperties_ItemOfInterestSum_get());
    public final static Measurement.DerivedDataProperties UsedForAnalysis = new Measurement.DerivedDataProperties("UsedForAnalysis", SpecUtilsSwigJNI.Measurement_DerivedDataProperties_UsedForAnalysis_get());
    public final static Measurement.DerivedDataProperties ProcessedFurther = new Measurement.DerivedDataProperties("ProcessedFurther", SpecUtilsSwigJNI.Measurement_DerivedDataProperties_ProcessedFurther_get());
    public final static Measurement.DerivedDataProperties BackgroundSubtracted = new Measurement.DerivedDataProperties("BackgroundSubtracted", SpecUtilsSwigJNI.Measurement_DerivedDataProperties_BackgroundSubtracted_get());
    public final static Measurement.DerivedDataProperties IsBackground = new Measurement.DerivedDataProperties("IsBackground", SpecUtilsSwigJNI.Measurement_DerivedDataProperties_IsBackground_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static DerivedDataProperties swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + DerivedDataProperties.class + " with value " + swigValue);
    }

    private DerivedDataProperties(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private DerivedDataProperties(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private DerivedDataProperties(String swigName, DerivedDataProperties swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static DerivedDataProperties[] swigValues = { IsDerived, ItemOfInterestSum, UsedForAnalysis, ProcessedFurther, BackgroundSubtracted, IsBackground };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
