/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class MultimediaData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MultimediaData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultimediaData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MultimediaData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_MultimediaData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRemark_(String value) {
    SpecUtilsSwigJNI.MultimediaData_remark__set(swigCPtr, this, value);
  }

  public String getRemark_() {
    return SpecUtilsSwigJNI.MultimediaData_remark__get(swigCPtr, this);
  }

  public void setDescriptions_(String value) {
    SpecUtilsSwigJNI.MultimediaData_descriptions__set(swigCPtr, this, value);
  }

  public String getDescriptions_() {
    return SpecUtilsSwigJNI.MultimediaData_descriptions__get(swigCPtr, this);
  }

  public void setData_(SWIGTYPE_p_std__vectorT_char_t value) {
    SpecUtilsSwigJNI.MultimediaData_data__set(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_char_t getData_() {
    long cPtr = SpecUtilsSwigJNI.MultimediaData_data__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_char_t(cPtr, false);
  }

  public void setData_encoding_(MultimediaData.EncodingType value) {
    SpecUtilsSwigJNI.MultimediaData_data_encoding__set(swigCPtr, this, value.swigValue());
  }

  public MultimediaData.EncodingType getData_encoding_() {
    return MultimediaData.EncodingType.swigToEnum(SpecUtilsSwigJNI.MultimediaData_data_encoding__get(swigCPtr, this));
  }

  public void setCapture_start_time_(SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t value) {
    SpecUtilsSwigJNI.MultimediaData_capture_start_time__set(swigCPtr, this, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t getCapture_start_time_() {
    return new SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t(SpecUtilsSwigJNI.MultimediaData_capture_start_time__get(swigCPtr, this), true);
  }

  public void setFile_uri_(String value) {
    SpecUtilsSwigJNI.MultimediaData_file_uri__set(swigCPtr, this, value);
  }

  public String getFile_uri_() {
    return SpecUtilsSwigJNI.MultimediaData_file_uri__get(swigCPtr, this);
  }

  public void setMime_type_(String value) {
    SpecUtilsSwigJNI.MultimediaData_mime_type__set(swigCPtr, this, value);
  }

  public String getMime_type_() {
    return SpecUtilsSwigJNI.MultimediaData_mime_type__get(swigCPtr, this);
  }

  public MultimediaData() {
    this(SpecUtilsSwigJNI.new_MultimediaData(), true);
  }

  public final static class EncodingType {
    public final static MultimediaData.EncodingType BinaryUTF8 = new MultimediaData.EncodingType("BinaryUTF8");
    public final static MultimediaData.EncodingType BinaryHex = new MultimediaData.EncodingType("BinaryHex");
    public final static MultimediaData.EncodingType BinaryBase64 = new MultimediaData.EncodingType("BinaryBase64");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static EncodingType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + EncodingType.class + " with value " + swigValue);
    }

    private EncodingType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private EncodingType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private EncodingType(String swigName, EncodingType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static EncodingType[] swigValues = { BinaryUTF8, BinaryHex, BinaryBase64 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
