/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class OccupancyStatus {
  public final static OccupancyStatus NotOccupied = new OccupancyStatus("NotOccupied");
  public final static OccupancyStatus Occupied = new OccupancyStatus("Occupied");
  public final static OccupancyStatus Unknown = new OccupancyStatus("Unknown");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OccupancyStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OccupancyStatus.class + " with value " + swigValue);
  }

  private OccupancyStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OccupancyStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OccupancyStatus(String swigName, OccupancyStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OccupancyStatus[] swigValues = { NotOccupied, Occupied, Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

