/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class ParserType {
  public final static ParserType N42_2006 = new ParserType("N42_2006");
  public final static ParserType N42_2012 = new ParserType("N42_2012");
  public final static ParserType Spc = new ParserType("Spc");
  public final static ParserType Exploranium = new ParserType("Exploranium");
  public final static ParserType Pcf = new ParserType("Pcf");
  public final static ParserType Chn = new ParserType("Chn");
  public final static ParserType SpeIaea = new ParserType("SpeIaea");
  public final static ParserType TxtOrCsv = new ParserType("TxtOrCsv");
  public final static ParserType Cnf = new ParserType("Cnf");
  public final static ParserType TracsMps = new ParserType("TracsMps");
  public final static ParserType Aram = new ParserType("Aram");
  public final static ParserType SPMDailyFile = new ParserType("SPMDailyFile");
  public final static ParserType AmptekMca = new ParserType("AmptekMca");
  public final static ParserType MicroRaider = new ParserType("MicroRaider");
  public final static ParserType RadiaCode = new ParserType("RadiaCode");
  public final static ParserType OrtecListMode = new ParserType("OrtecListMode");
  public final static ParserType LsrmSpe = new ParserType("LsrmSpe");
  public final static ParserType Tka = new ParserType("Tka");
  public final static ParserType MultiAct = new ParserType("MultiAct");
  public final static ParserType Phd = new ParserType("Phd");
  public final static ParserType Lzs = new ParserType("Lzs");
  public final static ParserType ScanDataXml = new ParserType("ScanDataXml");
  public final static ParserType Json = new ParserType("Json");
  public final static ParserType CaenHexagonGXml = new ParserType("CaenHexagonGXml");
  public final static ParserType Auto = new ParserType("Auto");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParserType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParserType.class + " with value " + swigValue);
  }

  private ParserType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParserType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParserType(String swigName, ParserType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParserType[] swigValues = { N42_2006, N42_2012, Spc, Exploranium, Pcf, Chn, SpeIaea, TxtOrCsv, Cnf, TracsMps, Aram, SPMDailyFile, AmptekMca, MicroRaider, RadiaCode, OrtecListMode, LsrmSpe, Tka, MultiAct, Phd, Lzs, ScanDataXml, Json, CaenHexagonGXml, Auto };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

