/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class QualityStatus {
  public final static QualityStatus Good = new QualityStatus("Good");
  public final static QualityStatus Suspect = new QualityStatus("Suspect");
  public final static QualityStatus Bad = new QualityStatus("Bad");
  public final static QualityStatus Missing = new QualityStatus("Missing");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static QualityStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + QualityStatus.class + " with value " + swigValue);
  }

  private QualityStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private QualityStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private QualityStatus(String swigName, QualityStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static QualityStatus[] swigValues = { Good, Suspect, Bad, Missing };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

