/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class SaveSpectrumAsType {
  public final static SaveSpectrumAsType Txt = new SaveSpectrumAsType("Txt");
  public final static SaveSpectrumAsType Csv = new SaveSpectrumAsType("Csv");
  public final static SaveSpectrumAsType Pcf = new SaveSpectrumAsType("Pcf");
  public final static SaveSpectrumAsType N42_2006 = new SaveSpectrumAsType("N42_2006");
  public final static SaveSpectrumAsType N42_2012 = new SaveSpectrumAsType("N42_2012");
  public final static SaveSpectrumAsType Chn = new SaveSpectrumAsType("Chn");
  public final static SaveSpectrumAsType SpcBinaryInt = new SaveSpectrumAsType("SpcBinaryInt");
  public final static SaveSpectrumAsType SpcBinaryFloat = new SaveSpectrumAsType("SpcBinaryFloat");
  public final static SaveSpectrumAsType SpcAscii = new SaveSpectrumAsType("SpcAscii");
  public final static SaveSpectrumAsType ExploraniumGr130v0 = new SaveSpectrumAsType("ExploraniumGr130v0");
  public final static SaveSpectrumAsType ExploraniumGr135v2 = new SaveSpectrumAsType("ExploraniumGr135v2");
  public final static SaveSpectrumAsType SpeIaea = new SaveSpectrumAsType("SpeIaea");
  public final static SaveSpectrumAsType Cnf = new SaveSpectrumAsType("Cnf");
  public final static SaveSpectrumAsType Tka = new SaveSpectrumAsType("Tka");
  public final static SaveSpectrumAsType HtmlD3 = new SaveSpectrumAsType("HtmlD3");
  public final static SaveSpectrumAsType NumTypes = new SaveSpectrumAsType("NumTypes");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SaveSpectrumAsType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SaveSpectrumAsType.class + " with value " + swigValue);
  }

  private SaveSpectrumAsType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SaveSpectrumAsType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SaveSpectrumAsType(String swigName, SaveSpectrumAsType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SaveSpectrumAsType[] swigValues = { Txt, Csv, Pcf, N42_2006, N42_2012, Chn, SpcBinaryInt, SpcBinaryFloat, SpcAscii, ExploraniumGr130v0, ExploraniumGr135v2, SpeIaea, Cnf, Tka, HtmlD3, NumTypes };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

