/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class SourceType {
  public final static SourceType IntrinsicActivity = new SourceType("IntrinsicActivity");
  public final static SourceType Calibration = new SourceType("Calibration");
  public final static SourceType Background = new SourceType("Background");
  public final static SourceType Foreground = new SourceType("Foreground");
  public final static SourceType Unknown = new SourceType("Unknown");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SourceType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SourceType.class + " with value " + swigValue);
  }

  private SourceType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SourceType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SourceType(String swigName, SourceType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SourceType[] swigValues = { IntrinsicActivity, Calibration, Background, Foreground, Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

