/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class SpecUtilsSwig implements SpecUtilsSwigConstants {
  public static SWIGTYPE_p_std__ostream openFile(String filename) {
    long cPtr = SpecUtilsSwigJNI.openFile(filename);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__ostream(cPtr, false);
  }

  public static void closeFile(SWIGTYPE_p_std__ostream stream) {
    SpecUtilsSwigJNI.closeFile(SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public static String descriptionText(SpectrumType type) {
    return SpecUtilsSwigJNI.descriptionText__SWIG_0(type.swigValue());
  }

  public static SpectrumType spectrumTypeFromDescription(String descrip) {
    return SpectrumType.swigToEnum(SpecUtilsSwigJNI.spectrumTypeFromDescription(descrip));
  }

  public static String suggestedNameEnding(SaveSpectrumAsType type) {
    return SpecUtilsSwigJNI.suggestedNameEnding(type.swigValue());
  }

  public static String descriptionText(SaveSpectrumAsType type) {
    return SpecUtilsSwigJNI.descriptionText__SWIG_1(type.swigValue());
  }

  public static boolean is_candidate_n42_file(String data) {
    return SpecUtilsSwigJNI.is_candidate_n42_file__SWIG_0(data);
  }

  public static boolean is_candidate_n42_file(String data, String data_end) {
    return SpecUtilsSwigJNI.is_candidate_n42_file__SWIG_1(data, data_end);
  }

  public static String convert_n42_utf16_xml_to_utf8(String data, String data_end) {
    return SpecUtilsSwigJNI.convert_n42_utf16_xml_to_utf8(data, data_end);
  }

  public static void add_analysis_results_to_2012_N42(DetectorAnalysis ana, SWIGTYPE_p_rapidxml__xml_nodeT_char_t RadInstrumentData, SWIGTYPE_p_std__mutex xmldocmutex) {
    SpecUtilsSwigJNI.add_analysis_results_to_2012_N42(DetectorAnalysis.getCPtr(ana), ana, SWIGTYPE_p_rapidxml__xml_nodeT_char_t.getCPtr(RadInstrumentData), SWIGTYPE_p_std__mutex.getCPtr(xmldocmutex));
  }

  public static void set_analysis_info_from_n42(SWIGTYPE_p_rapidxml__xml_nodeT_char_t analysis_node, DetectorAnalysis analysis) {
    SpecUtilsSwigJNI.set_analysis_info_from_n42(SWIGTYPE_p_rapidxml__xml_nodeT_char_t.getCPtr(analysis_node), DetectorAnalysis.getCPtr(analysis), analysis);
  }

  public static double gamma_integral(Measurement hist, float lowenergy, float upperunergy) {
    return SpecUtilsSwigJNI.gamma_integral(Measurement.getCPtr(hist), hist, lowenergy, upperunergy);
  }

  public static String detectorTypeToString(DetectorType type) {
    return SpecUtilsSwigJNI.detectorTypeToString(type.swigValue());
  }

  public static SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_t energy_cal_combine_channels(EnergyCalibration orig_cal, long num_channel_combine) {
    return new SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_t(SpecUtilsSwigJNI.energy_cal_combine_channels(EnergyCalibration.getCPtr(orig_cal), orig_cal, num_channel_combine), true);
  }

  public static FloatVector polynomial_binning(FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs) {
    long cPtr = SpecUtilsSwigJNI.polynomial_binning(FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs));
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public static FloatVector fullrangefraction_binning(FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs, boolean include_upper_energy) {
    long cPtr = SpecUtilsSwigJNI.fullrangefraction_binning__SWIG_0(FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs), include_upper_energy);
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public static FloatVector fullrangefraction_binning(FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    long cPtr = SpecUtilsSwigJNI.fullrangefraction_binning__SWIG_1(FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public static double fullrangefraction_energy(double channel_number, FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs) {
    return SpecUtilsSwigJNI.fullrangefraction_energy(channel_number, FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs));
  }

  public static double polynomial_energy(double channel_number, FloatVector coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs) {
    return SpecUtilsSwigJNI.polynomial_energy(channel_number, FloatVector.getCPtr(coeffs), coeffs, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs));
  }

  public static double deviation_pair_correction(double polynomial_energy, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    return SpecUtilsSwigJNI.deviation_pair_correction(polynomial_energy, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
  }

  public static double correction_due_to_dev_pairs(double true_energy, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    return SpecUtilsSwigJNI.correction_due_to_dev_pairs(true_energy, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
  }

  public static FloatVector apply_deviation_pair(FloatVector binning, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t dev_pairs) {
    long cPtr = SpecUtilsSwigJNI.apply_deviation_pair(FloatVector.getCPtr(binning), binning, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(dev_pairs));
    return (cPtr == 0) ? null : new FloatVector(cPtr, true);
  }

  public static FloatVector polynomial_coef_to_fullrangefraction(FloatVector coeffs, long nchannel) {
    return new FloatVector(SpecUtilsSwigJNI.polynomial_coef_to_fullrangefraction(FloatVector.getCPtr(coeffs), coeffs, nchannel), true);
  }

  public static FloatVector fullrangefraction_coef_to_polynomial(FloatVector coeffs, long nchannel) {
    return new FloatVector(SpecUtilsSwigJNI.fullrangefraction_coef_to_polynomial(FloatVector.getCPtr(coeffs), coeffs, nchannel), true);
  }

  public static FloatVector mid_channel_polynomial_to_fullrangeFraction(FloatVector coeffs, long nchannel) {
    return new FloatVector(SpecUtilsSwigJNI.mid_channel_polynomial_to_fullrangeFraction(FloatVector.getCPtr(coeffs), coeffs, nchannel), true);
  }

  public static boolean calibration_is_valid(EnergyCalType type, FloatVector eqn, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t devpairs, long nbin) {
    return SpecUtilsSwigJNI.calibration_is_valid(type.swigValue(), FloatVector.getCPtr(eqn), eqn, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(devpairs), nbin);
  }

  public static FloatVector polynomial_cal_remove_first_channels(int num_channels_remove, FloatVector orig_coefs) {
    return new FloatVector(SpecUtilsSwigJNI.polynomial_cal_remove_first_channels(num_channels_remove, FloatVector.getCPtr(orig_coefs), orig_coefs), true);
  }

  public static double find_fullrangefraction_channel(double energy, FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs, double accuracy) {
    return SpecUtilsSwigJNI.find_fullrangefraction_channel__SWIG_0(energy, FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs), accuracy);
  }

  public static double find_fullrangefraction_channel(double energy, FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs) {
    return SpecUtilsSwigJNI.find_fullrangefraction_channel__SWIG_1(energy, FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs));
  }

  public static double find_polynomial_channel(double energy, FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs, double accuracy) {
    return SpecUtilsSwigJNI.find_polynomial_channel__SWIG_0(energy, FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs), accuracy);
  }

  public static double find_polynomial_channel(double energy, FloatVector coeffs, long nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t deviation_pairs) {
    return SpecUtilsSwigJNI.find_polynomial_channel__SWIG_1(energy, FloatVector.getCPtr(coeffs), coeffs, nchannel, SWIGTYPE_p_std__vectorT_std__pairT_float_float_t_t.getCPtr(deviation_pairs));
  }

  public static void rebin_by_lower_edge(FloatVector original_energies, FloatVector original_counts, FloatVector new_energies, FloatVector resulting_counts) {
    SpecUtilsSwigJNI.rebin_by_lower_edge(FloatVector.getCPtr(original_energies), original_energies, FloatVector.getCPtr(original_counts), original_counts, FloatVector.getCPtr(new_energies), new_energies, FloatVector.getCPtr(resulting_counts), resulting_counts);
  }

  public static SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_t energy_cal_from_CALp_file(SWIGTYPE_p_std__istream input, long num_channels, SWIGTYPE_p_std__string det_name) {
    return new SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_t(SpecUtilsSwigJNI.energy_cal_from_CALp_file(SWIGTYPE_p_std__istream.getCPtr(input), num_channels, SWIGTYPE_p_std__string.getCPtr(det_name)), true);
  }

  public static boolean write_CALp_file(SWIGTYPE_p_std__ostream output, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal, String detector_name) {
    return SpecUtilsSwigJNI.write_CALp_file(SWIGTYPE_p_std__ostream.getCPtr(output), SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal), detector_name);
  }

  public static SWIGTYPE_p_unsigned_char getD3_MIN_JS() {
    long cPtr = SpecUtilsSwigJNI.D3_MIN_JS_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static long getD3_MIN_JS_SIZE() {
    return SpecUtilsSwigJNI.D3_MIN_JS_SIZE_get();
  }

  public static SWIGTYPE_p_unsigned_char getSPECTRUM_CHART_D3_JS() {
    long cPtr = SpecUtilsSwigJNI.SPECTRUM_CHART_D3_JS_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static long getSPECTRUM_CHART_D3_JS_SIZE() {
    return SpecUtilsSwigJNI.SPECTRUM_CHART_D3_JS_SIZE_get();
  }

  public static SWIGTYPE_p_unsigned_char getSPECTRUM_CHART_D3_CSS() {
    long cPtr = SpecUtilsSwigJNI.SPECTRUM_CHART_D3_CSS_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static long getSPECTRUM_CHART_D3_CSS_SIZE() {
    return SpecUtilsSwigJNI.SPECTRUM_CHART_D3_CSS_SIZE_get();
  }

  public static SWIGTYPE_p_unsigned_char getSPECTRUM_CHART_D3_STANDALONE_CSS() {
    long cPtr = SpecUtilsSwigJNI.SPECTRUM_CHART_D3_STANDALONE_CSS_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static long getSPECTRUM_CHART_D3_STANDALONE_CSS_SIZE() {
    return SpecUtilsSwigJNI.SPECTRUM_CHART_D3_STANDALONE_CSS_SIZE_get();
  }

  public static boolean write_spectrum_data_js(SWIGTYPE_p_std__ostream ostr, Measurement meas, D3SpectrumOptions options, long specID, int backgroundID) {
    return SpecUtilsSwigJNI.write_spectrum_data_js(SWIGTYPE_p_std__ostream.getCPtr(ostr), Measurement.getCPtr(meas), meas, D3SpectrumOptions.getCPtr(options), options, specID, backgroundID);
  }

  public static boolean write_d3_html(SWIGTYPE_p_std__ostream ostr, SWIGTYPE_p_std__vectorT_std__pairT_SpecUtils__Measurement_const_p_D3SpectrumExport__D3SpectrumOptions_t_t measurements, D3SpectrumChartOptions options) {
    return SpecUtilsSwigJNI.write_d3_html(SWIGTYPE_p_std__ostream.getCPtr(ostr), SWIGTYPE_p_std__vectorT_std__pairT_SpecUtils__Measurement_const_p_D3SpectrumExport__D3SpectrumOptions_t_t.getCPtr(measurements), D3SpectrumChartOptions.getCPtr(options), options);
  }

  public static boolean write_html_page_header(SWIGTYPE_p_std__ostream ostr, String page_title) {
    return SpecUtilsSwigJNI.write_html_page_header(SWIGTYPE_p_std__ostream.getCPtr(ostr), page_title);
  }

  public static boolean write_js_for_chart(SWIGTYPE_p_std__ostream ostr, String div_name, String chart_title, String x_axis_title, String y_axis_title) {
    return SpecUtilsSwigJNI.write_js_for_chart(SWIGTYPE_p_std__ostream.getCPtr(ostr), div_name, chart_title, x_axis_title, y_axis_title);
  }

  public static boolean write_and_set_data_for_chart(SWIGTYPE_p_std__ostream ostr, String div_name, SWIGTYPE_p_std__vectorT_std__pairT_SpecUtils__Measurement_const_p_D3SpectrumExport__D3SpectrumOptions_t_t measurements) {
    return SpecUtilsSwigJNI.write_and_set_data_for_chart(SWIGTYPE_p_std__ostream.getCPtr(ostr), div_name, SWIGTYPE_p_std__vectorT_std__pairT_SpecUtils__Measurement_const_p_D3SpectrumExport__D3SpectrumOptions_t_t.getCPtr(measurements));
  }

  public static boolean write_set_options_for_chart(SWIGTYPE_p_std__ostream ostr, String div_name, D3SpectrumChartOptions options) {
    return SpecUtilsSwigJNI.write_set_options_for_chart(SWIGTYPE_p_std__ostream.getCPtr(ostr), div_name, D3SpectrumChartOptions.getCPtr(options), options);
  }

  public static boolean write_html_display_options_for_chart(SWIGTYPE_p_std__ostream ostr, String div_name, D3SpectrumChartOptions options) {
    return SpecUtilsSwigJNI.write_html_display_options_for_chart(SWIGTYPE_p_std__ostream.getCPtr(ostr), div_name, D3SpectrumChartOptions.getCPtr(options), options);
  }

  public static SWIGTYPE_p_unsigned_char d3_js() {
    long cPtr = SpecUtilsSwigJNI.d3_js();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_char spectrum_chart_d3_js() {
    long cPtr = SpecUtilsSwigJNI.spectrum_chart_d3_js();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_char spectrum_char_d3_css() {
    long cPtr = SpecUtilsSwigJNI.spectrum_char_d3_css();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_char spectrum_chart_d3_standalone_css() {
    long cPtr = SpecUtilsSwigJNI.spectrum_chart_d3_standalone_css();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static String spectrum_chart_setup_js() {
    return SpecUtilsSwigJNI.spectrum_chart_setup_js();
  }

}
