/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class SpecFile {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpecFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpecFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SpecFile obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_SpecFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SpecFile() {
    this(SpecUtilsSwigJNI.new_SpecFile__SWIG_0(), true);
  }

  public SpecFile(SpecFile rhs) {
    this(SpecUtilsSwigJNI.new_SpecFile__SWIG_1(SpecFile.getCPtr(rhs), rhs), true);
  }

  public SpecFile operatorEqual(SpecFile rhs) {
    return new SpecFile(SpecUtilsSwigJNI.SpecFile_operatorEqual(swigCPtr, this, SpecFile.getCPtr(rhs), rhs), false);
  }

  public boolean load_file(String filename, ParserType parser_type, String file_ending_hint) {
    return SpecUtilsSwigJNI.SpecFile_load_file(swigCPtr, this, filename, parser_type.swigValue(), file_ending_hint);
  }

  public StringVector parse_warnings() {
    return new StringVector(SpecUtilsSwigJNI.SpecFile_parse_warnings(swigCPtr, this), false);
  }

  public boolean modified() {
    return SpecUtilsSwigJNI.SpecFile_modified(swigCPtr, this);
  }

  public void reset_modified() {
    SpecUtilsSwigJNI.SpecFile_reset_modified(swigCPtr, this);
  }

  public boolean modified_since_decode() {
    return SpecUtilsSwigJNI.SpecFile_modified_since_decode(swigCPtr, this);
  }

  public void reset_modified_since_decode() {
    SpecUtilsSwigJNI.SpecFile_reset_modified_since_decode(swigCPtr, this);
  }

  public float gamma_live_time() {
    return SpecUtilsSwigJNI.SpecFile_gamma_live_time(swigCPtr, this);
  }

  public float gamma_real_time() {
    return SpecUtilsSwigJNI.SpecFile_gamma_real_time(swigCPtr, this);
  }

  public double gamma_count_sum() {
    return SpecUtilsSwigJNI.SpecFile_gamma_count_sum(swigCPtr, this);
  }

  public double neutron_counts_sum() {
    return SpecUtilsSwigJNI.SpecFile_neutron_counts_sum(swigCPtr, this);
  }

  public String filename() {
    return SpecUtilsSwigJNI.SpecFile_filename(swigCPtr, this);
  }

  public StringVector detector_names() {
    return new StringVector(SpecUtilsSwigJNI.SpecFile_detector_names(swigCPtr, this), false);
  }

  public IntVector detector_numbers() {
    return new IntVector(SpecUtilsSwigJNI.SpecFile_detector_numbers(swigCPtr, this), false);
  }

  public StringVector gamma_detector_names() {
    return new StringVector(SpecUtilsSwigJNI.SpecFile_gamma_detector_names(swigCPtr, this), false);
  }

  public StringVector neutron_detector_names() {
    return new StringVector(SpecUtilsSwigJNI.SpecFile_neutron_detector_names(swigCPtr, this), false);
  }

  public String uuid() {
    return SpecUtilsSwigJNI.SpecFile_uuid(swigCPtr, this);
  }

  public StringVector remarks() {
    return new StringVector(SpecUtilsSwigJNI.SpecFile_remarks(swigCPtr, this), false);
  }

  public int lane_number() {
    return SpecUtilsSwigJNI.SpecFile_lane_number(swigCPtr, this);
  }

  public String measurement_location_name() {
    return SpecUtilsSwigJNI.SpecFile_measurement_location_name(swigCPtr, this);
  }

  public String inspection() {
    return SpecUtilsSwigJNI.SpecFile_inspection(swigCPtr, this);
  }

  public String measurement_operator() {
    return SpecUtilsSwigJNI.SpecFile_measurement_operator(swigCPtr, this);
  }

  public SWIGTYPE_p_std__setT_int_t sample_numbers() {
    return new SWIGTYPE_p_std__setT_int_t(SpecUtilsSwigJNI.SpecFile_sample_numbers(swigCPtr, this), false);
  }

  public long num_measurements() {
    return SpecUtilsSwigJNI.SpecFile_num_measurements(swigCPtr, this);
  }

  public DetectorType detector_type() {
    return DetectorType.swigToEnum(SpecUtilsSwigJNI.SpecFile_detector_type(swigCPtr, this));
  }

  public String instrument_type() {
    return SpecUtilsSwigJNI.SpecFile_instrument_type(swigCPtr, this);
  }

  public String manufacturer() {
    return SpecUtilsSwigJNI.SpecFile_manufacturer(swigCPtr, this);
  }

  public String instrument_model() {
    return SpecUtilsSwigJNI.SpecFile_instrument_model(swigCPtr, this);
  }

  public String instrument_id() {
    return SpecUtilsSwigJNI.SpecFile_instrument_id(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__Measurement_const_t_t measurements() {
    return new SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__Measurement_const_t_t(SpecUtilsSwigJNI.SpecFile_measurements(swigCPtr, this), true);
  }

  public Measurement measurement(long num) {
    long cPtr = SpecUtilsSwigJNI.SpecFile_measurement__SWIG_0(swigCPtr, this, num);
    return (cPtr == 0) ? null : new Measurement(cPtr, true);
  }

  public SWIGTYPE_p_std__shared_ptrT_SpecUtils__DetectorAnalysis_const_t detectors_analysis() {
    return new SWIGTYPE_p_std__shared_ptrT_SpecUtils__DetectorAnalysis_const_t(SpecUtilsSwigJNI.SpecFile_detectors_analysis(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__MultimediaData_const_t_t multimedia_data() {
    return new SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__MultimediaData_const_t_t(SpecUtilsSwigJNI.SpecFile_multimedia_data(swigCPtr, this), false);
  }

  public boolean has_gps_info() {
    return SpecUtilsSwigJNI.SpecFile_has_gps_info(swigCPtr, this);
  }

  public double mean_latitude() {
    return SpecUtilsSwigJNI.SpecFile_mean_latitude(swigCPtr, this);
  }

  public double mean_longitude() {
    return SpecUtilsSwigJNI.SpecFile_mean_longitude(swigCPtr, this);
  }

  public boolean passthrough() {
    return SpecUtilsSwigJNI.SpecFile_passthrough(swigCPtr, this);
  }

  public boolean contains_derived_data() {
    return SpecUtilsSwigJNI.SpecFile_contains_derived_data(swigCPtr, this);
  }

  public boolean contains_non_derived_data() {
    return SpecUtilsSwigJNI.SpecFile_contains_non_derived_data(swigCPtr, this);
  }

  public void set_filename(String n) {
    SpecUtilsSwigJNI.SpecFile_set_filename(swigCPtr, this, n);
  }

  public void set_remarks(StringVector n) {
    SpecUtilsSwigJNI.SpecFile_set_remarks__SWIG_0(swigCPtr, this, StringVector.getCPtr(n), n);
  }

  public void add_remark(String remark) {
    SpecUtilsSwigJNI.SpecFile_add_remark(swigCPtr, this, remark);
  }

  public void set_parse_warnings(StringVector warnings) {
    SpecUtilsSwigJNI.SpecFile_set_parse_warnings(swigCPtr, this, StringVector.getCPtr(warnings), warnings);
  }

  public void set_uuid(String n) {
    SpecUtilsSwigJNI.SpecFile_set_uuid(swigCPtr, this, n);
  }

  public void set_lane_number(int num) {
    SpecUtilsSwigJNI.SpecFile_set_lane_number(swigCPtr, this, num);
  }

  public void set_measurement_location_name(String n) {
    SpecUtilsSwigJNI.SpecFile_set_measurement_location_name(swigCPtr, this, n);
  }

  public void set_inspection(String n) {
    SpecUtilsSwigJNI.SpecFile_set_inspection(swigCPtr, this, n);
  }

  public void set_instrument_type(String n) {
    SpecUtilsSwigJNI.SpecFile_set_instrument_type(swigCPtr, this, n);
  }

  public void set_detector_type(DetectorType type) {
    SpecUtilsSwigJNI.SpecFile_set_detector_type(swigCPtr, this, type.swigValue());
  }

  public void set_manufacturer(String n) {
    SpecUtilsSwigJNI.SpecFile_set_manufacturer(swigCPtr, this, n);
  }

  public void set_instrument_model(String n) {
    SpecUtilsSwigJNI.SpecFile_set_instrument_model(swigCPtr, this, n);
  }

  public void set_instrument_id(String n) {
    SpecUtilsSwigJNI.SpecFile_set_instrument_id(swigCPtr, this, n);
  }

  public void set_live_time(float lt, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_live_time(swigCPtr, this, lt, Measurement.getCPtr(measurement), measurement);
  }

  public void set_real_time(float rt, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_real_time(swigCPtr, this, rt, Measurement.getCPtr(measurement), measurement);
  }

  public void set_start_time(SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t timestamp, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_start_time(swigCPtr, this, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t.getCPtr(timestamp), Measurement.getCPtr(measurement), measurement);
  }

  public void set_remarks(StringVector remarks, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_remarks__SWIG_1(swigCPtr, this, StringVector.getCPtr(remarks), remarks, Measurement.getCPtr(measurement), measurement);
  }

  public void set_source_type(SourceType type, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_source_type(swigCPtr, this, type.swigValue(), Measurement.getCPtr(measurement), measurement);
  }

  public void set_position(double longitude, double latitude, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t position_time, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_position(swigCPtr, this, longitude, latitude, SWIGTYPE_p_std__chrono__time_pointT_std__chrono__system_clock_std__chrono__microseconds_t.getCPtr(position_time), Measurement.getCPtr(measurement), measurement);
  }

  public void set_title(String title, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_title(swigCPtr, this, title, Measurement.getCPtr(measurement), measurement);
  }

  public void set_contained_neutrons(boolean contained, float counts, Measurement measurement, float neutron_live_time) {
    SpecUtilsSwigJNI.SpecFile_set_contained_neutrons(swigCPtr, this, contained, counts, Measurement.getCPtr(measurement), measurement, neutron_live_time);
  }

  public void set_detectors_analysis(DetectorAnalysis ana) {
    SpecUtilsSwigJNI.SpecFile_set_detectors_analysis(swigCPtr, this, DetectorAnalysis.getCPtr(ana), ana);
  }

  public void change_detector_name(String original_name, String new_name) {
    SpecUtilsSwigJNI.SpecFile_change_detector_name(swigCPtr, this, original_name, new_name);
  }

  public void change_sample_numbers(SWIGTYPE_p_std__vectorT_std__pairT_int_int_t_t from_to_sample_nums) {
    SpecUtilsSwigJNI.SpecFile_change_sample_numbers(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__pairT_int_int_t_t.getCPtr(from_to_sample_nums));
  }

  public void add_measurement(Measurement meas, boolean doCleanup) {
    SpecUtilsSwigJNI.SpecFile_add_measurement(swigCPtr, this, Measurement.getCPtr(meas), meas, doCleanup);
  }

  public void remove_measurement(Measurement meas, boolean doCleanup) {
    SpecUtilsSwigJNI.SpecFile_remove_measurement(swigCPtr, this, Measurement.getCPtr(meas), meas, doCleanup);
  }

  public void remove_measurements(SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__Measurement_const_t_t meas) {
    SpecUtilsSwigJNI.SpecFile_remove_measurements(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__Measurement_const_t_t.getCPtr(meas));
  }

  public void clear_multimedia_data() {
    SpecUtilsSwigJNI.SpecFile_clear_multimedia_data(swigCPtr, this);
  }

  public void add_multimedia_data(MultimediaData data) {
    SpecUtilsSwigJNI.SpecFile_add_multimedia_data(swigCPtr, this, MultimediaData.getCPtr(data), data);
  }

  public void set_multimedia_data(SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__MultimediaData_const_t_t data) {
    SpecUtilsSwigJNI.SpecFile_set_multimedia_data(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__MultimediaData_const_t_t.getCPtr(data));
  }

  public long combine_gamma_channels(long ncombine, long nchannels) {
    return SpecUtilsSwigJNI.SpecFile_combine_gamma_channels__SWIG_0(swigCPtr, this, ncombine, nchannels);
  }

  public void combine_gamma_channels(long ncombine, Measurement m) {
    SpecUtilsSwigJNI.SpecFile_combine_gamma_channels__SWIG_1(swigCPtr, this, ncombine, Measurement.getCPtr(m), m);
  }

  public long truncate_gamma_channels(long keep_first_channel, long keep_last_channel, long nchannels, boolean keep_under_over_flow) {
    return SpecUtilsSwigJNI.SpecFile_truncate_gamma_channels__SWIG_0(swigCPtr, this, keep_first_channel, keep_last_channel, nchannels, keep_under_over_flow);
  }

  public void truncate_gamma_channels(long keep_first_channel, long keep_last_channel, boolean keep_under_over_flow, Measurement m) {
    SpecUtilsSwigJNI.SpecFile_truncate_gamma_channels__SWIG_1(swigCPtr, this, keep_first_channel, keep_last_channel, keep_under_over_flow, Measurement.getCPtr(m), m);
  }

  public int occupancy_number_from_remarks() {
    return SpecUtilsSwigJNI.SpecFile_occupancy_number_from_remarks(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__Measurement_const_t_t sample_measurements(int sample_number) {
    return new SWIGTYPE_p_std__vectorT_std__shared_ptrT_SpecUtils__Measurement_const_t_t(SpecUtilsSwigJNI.SpecFile_sample_measurements(swigCPtr, this, sample_number), true);
  }

  public Measurement measurement(int sample_number, String det_name) {
    long cPtr = SpecUtilsSwigJNI.SpecFile_measurement__SWIG_1(swigCPtr, this, sample_number, det_name);
    return (cPtr == 0) ? null : new Measurement(cPtr, true);
  }

  public Measurement measurement(int sample_number, int detector_number) {
    long cPtr = SpecUtilsSwigJNI.SpecFile_measurement__SWIG_2(swigCPtr, this, sample_number, detector_number);
    return (cPtr == 0) ? null : new Measurement(cPtr, true);
  }

  public SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t suggested_sum_energy_calibration(SWIGTYPE_p_std__setT_int_t sample_numbers, StringVector detector_names) {
    return new SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t(SpecUtilsSwigJNI.SpecFile_suggested_sum_energy_calibration(swigCPtr, this, SWIGTYPE_p_std__setT_int_t.getCPtr(sample_numbers), StringVector.getCPtr(detector_names), detector_names), true);
  }

  public Measurement sum_measurements(SWIGTYPE_p_std__setT_int_t sample_numbers, StringVector detector_names, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t energy_cal) {
    long cPtr = SpecUtilsSwigJNI.SpecFile_sum_measurements(swigCPtr, this, SWIGTYPE_p_std__setT_int_t.getCPtr(sample_numbers), StringVector.getCPtr(detector_names), detector_names, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(energy_cal));
    return (cPtr == 0) ? null : new Measurement(cPtr, true);
  }

  public long memmorysize() {
    return SpecUtilsSwigJNI.SpecFile_memmorysize(swigCPtr, this);
  }

  public SWIGTYPE_p_std__setT_size_t_t gamma_channel_counts() {
    return new SWIGTYPE_p_std__setT_size_t_t(SpecUtilsSwigJNI.SpecFile_gamma_channel_counts(swigCPtr, this), true);
  }

  public long num_gamma_channels() {
    return SpecUtilsSwigJNI.SpecFile_num_gamma_channels(swigCPtr, this);
  }

  public long keep_n_bin_spectra_only(long nbin) {
    return SpecUtilsSwigJNI.SpecFile_keep_n_bin_spectra_only(swigCPtr, this, nbin);
  }

  public boolean contained_neutron() {
    return SpecUtilsSwigJNI.SpecFile_contained_neutron(swigCPtr, this);
  }

  public SWIGTYPE_p_std__setT_std__string_t energy_cal_variants() {
    return new SWIGTYPE_p_std__setT_std__string_t(SpecUtilsSwigJNI.SpecFile_energy_cal_variants(swigCPtr, this), true);
  }

  public long keep_energy_cal_variants(SWIGTYPE_p_std__setT_std__string_t variants) {
    return SpecUtilsSwigJNI.SpecFile_keep_energy_cal_variants(swigCPtr, this, SWIGTYPE_p_std__setT_std__string_t.getCPtr(variants));
  }

  public long keep_derived_data_variant(SpecFile.DerivedVariantToKeep tokeep) {
    return SpecUtilsSwigJNI.SpecFile_keep_derived_data_variant(swigCPtr, this, tokeep.swigValue());
  }

  public long remove_detectors_data(SWIGTYPE_p_std__setT_std__string_t dets_to_remove) {
    return SpecUtilsSwigJNI.SpecFile_remove_detectors_data(swigCPtr, this, SWIGTYPE_p_std__setT_std__string_t.getCPtr(dets_to_remove));
  }

  public long remove_neutron_measurements() {
    return SpecUtilsSwigJNI.SpecFile_remove_neutron_measurements(swigCPtr, this);
  }

  public int background_sample_number() {
    return SpecUtilsSwigJNI.SpecFile_background_sample_number(swigCPtr, this);
  }

  public String generate_psuedo_uuid() {
    return SpecUtilsSwigJNI.SpecFile_generate_psuedo_uuid(swigCPtr, this);
  }

  public void reset() {
    SpecUtilsSwigJNI.SpecFile_reset(swigCPtr, this);
  }

  public boolean load_N42_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_N42_file(swigCPtr, this, filename);
  }

  public boolean load_pcf_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_pcf_file(swigCPtr, this, filename);
  }

  public boolean load_spc_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_spc_file(swigCPtr, this, filename);
  }

  public boolean load_chn_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_chn_file(swigCPtr, this, filename);
  }

  public boolean load_iaea_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_iaea_file(swigCPtr, this, filename);
  }

  public boolean load_binary_exploranium_file(String file_name) {
    return SpecUtilsSwigJNI.SpecFile_load_binary_exploranium_file(swigCPtr, this, file_name);
  }

  public boolean load_micro_raider_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_micro_raider_file(swigCPtr, this, filename);
  }

  public boolean load_txt_or_csv_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_txt_or_csv_file(swigCPtr, this, filename);
  }

  public boolean load_cnf_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_cnf_file(swigCPtr, this, filename);
  }

  public boolean load_tracs_mps_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_tracs_mps_file(swigCPtr, this, filename);
  }

  public boolean load_aram_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_aram_file(swigCPtr, this, filename);
  }

  public boolean load_spectroscopic_daily_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_spectroscopic_daily_file(swigCPtr, this, filename);
  }

  public boolean load_amptek_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_amptek_file(swigCPtr, this, filename);
  }

  public boolean load_ortec_listmode_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_ortec_listmode_file(swigCPtr, this, filename);
  }

  public boolean load_lsrm_spe_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_lsrm_spe_file(swigCPtr, this, filename);
  }

  public boolean load_tka_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_tka_file(swigCPtr, this, filename);
  }

  public boolean load_multiact_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_multiact_file(swigCPtr, this, filename);
  }

  public boolean load_phd_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_phd_file(swigCPtr, this, filename);
  }

  public boolean load_lzs_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_lzs_file(swigCPtr, this, filename);
  }

  public boolean load_radiacode_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_radiacode_file(swigCPtr, this, filename);
  }

  public boolean load_xml_scan_data_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_xml_scan_data_file(swigCPtr, this, filename);
  }

  public boolean load_json_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_json_file(swigCPtr, this, filename);
  }

  public boolean load_caen_gxml_file(String filename) {
    return SpecUtilsSwigJNI.SpecFile_load_caen_gxml_file(swigCPtr, this, filename);
  }

  public boolean load_from_N42(SWIGTYPE_p_std__istream istr) {
    return SpecUtilsSwigJNI.SpecFile_load_from_N42(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr));
  }

  public boolean load_N42_from_data(String data) {
    return SpecUtilsSwigJNI.SpecFile_load_N42_from_data__SWIG_0(swigCPtr, this, data);
  }

  public boolean load_N42_from_data(String data, String data_end) {
    return SpecUtilsSwigJNI.SpecFile_load_N42_from_data__SWIG_1(swigCPtr, this, data, data_end);
  }

  public boolean load_from_iaea_spc(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_iaea_spc(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_binary_spc(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_binary_spc(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_N42_document(SWIGTYPE_p_rapidxml__xml_nodeT_char_t document_node) {
    return SpecUtilsSwigJNI.SpecFile_load_from_N42_document(swigCPtr, this, SWIGTYPE_p_rapidxml__xml_nodeT_char_t.getCPtr(document_node));
  }

  public boolean load_from_micro_raider_from_data(String data) {
    return SpecUtilsSwigJNI.SpecFile_load_from_micro_raider_from_data(swigCPtr, this, data);
  }

  public boolean load_from_binary_exploranium(SWIGTYPE_p_std__istream istr) {
    return SpecUtilsSwigJNI.SpecFile_load_from_binary_exploranium(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr));
  }

  public boolean load_from_pcf(SWIGTYPE_p_std__istream istr) {
    return SpecUtilsSwigJNI.SpecFile_load_from_pcf(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr));
  }

  public boolean load_from_txt_or_csv(SWIGTYPE_p_std__istream istr) {
    return SpecUtilsSwigJNI.SpecFile_load_from_txt_or_csv(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr));
  }

  public boolean load_from_Gr135_txt(SWIGTYPE_p_std__istream istr) {
    return SpecUtilsSwigJNI.SpecFile_load_from_Gr135_txt(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr));
  }

  public boolean load_from_spectroscopic_daily_file(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_spectroscopic_daily_file(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_srpm210_csv(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_srpm210_csv(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_D3S_raw(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_D3S_raw(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_amptek_mca(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_amptek_mca(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_ortec_listmode(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_ortec_listmode(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_lsrm_spe(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_lsrm_spe(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_tka(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_tka(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_multiact(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_multiact(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_phd(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_phd(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_lzs(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_lzs(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_radiacode(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_radiacode(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_radiacode_spectrogram(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_radiacode_spectrogram(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_xml_scan_data(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_xml_scan_data(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_iaea(SWIGTYPE_p_std__istream istr) {
    return SpecUtilsSwigJNI.SpecFile_load_from_iaea(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr));
  }

  public boolean load_from_chn(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_chn(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_cnf(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_cnf(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_tracs_mps(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_tracs_mps(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_aram(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_aram(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_json(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_json(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public boolean load_from_caen_gxml(SWIGTYPE_p_std__istream input) {
    return SpecUtilsSwigJNI.SpecFile_load_from_caen_gxml(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public void cleanup_after_load(long flags) {
    SpecUtilsSwigJNI.SpecFile_cleanup_after_load__SWIG_0(swigCPtr, this, flags);
  }

  public void cleanup_after_load() {
    SpecUtilsSwigJNI.SpecFile_cleanup_after_load__SWIG_1(swigCPtr, this);
  }

  public void recalc_total_counts() {
    SpecUtilsSwigJNI.SpecFile_recalc_total_counts(swigCPtr, this);
  }

  public void merge_neutron_meas_into_gamma_meas() {
    SpecUtilsSwigJNI.SpecFile_merge_neutron_meas_into_gamma_meas(swigCPtr, this);
  }

  public void rebin_measurement(SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_rebin_measurement(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal), Measurement.getCPtr(measurement), measurement);
  }

  public void rebin_all_measurements(SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal) {
    SpecUtilsSwigJNI.SpecFile_rebin_all_measurements(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal));
  }

  public void set_energy_calibration(SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal, Measurement measurement) {
    SpecUtilsSwigJNI.SpecFile_set_energy_calibration__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal), Measurement.getCPtr(measurement), measurement);
  }

  public long set_energy_calibration(SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t cal, SWIGTYPE_p_std__setT_int_t sample_numbers, StringVector detector_names) {
    return SpecUtilsSwigJNI.SpecFile_set_energy_calibration__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_SpecUtils__EnergyCalibration_const_t.getCPtr(cal), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_numbers), StringVector.getCPtr(detector_names), detector_names);
  }

  public void set_energy_calibration_from_CALp_file(SWIGTYPE_p_std__istream input) {
    SpecUtilsSwigJNI.SpecFile_set_energy_calibration_from_CALp_file(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(input));
  }

  public SWIGTYPE_p_std__setT_int_t detector_names_to_numbers(StringVector det_names) {
    return new SWIGTYPE_p_std__setT_int_t(SpecUtilsSwigJNI.SpecFile_detector_names_to_numbers(swigCPtr, this, StringVector.getCPtr(det_names), det_names), true);
  }

  public void write_to_file(String filename, SaveSpectrumAsType format) {
    SpecUtilsSwigJNI.SpecFile_write_to_file__SWIG_0(swigCPtr, this, filename, format.swigValue());
  }

  public void write_to_file(String filename, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums, SaveSpectrumAsType format) {
    SpecUtilsSwigJNI.SpecFile_write_to_file__SWIG_1(swigCPtr, this, filename, SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums), format.swigValue());
  }

  public void write_to_file(String filename, IntVector sample_nums, IntVector det_nums, SaveSpectrumAsType format) {
    SpecUtilsSwigJNI.SpecFile_write_to_file__SWIG_2(swigCPtr, this, filename, IntVector.getCPtr(sample_nums), sample_nums, IntVector.getCPtr(det_nums), det_nums, format.swigValue());
  }

  public void write_to_file(String filename, SWIGTYPE_p_std__setT_int_t sample_nums, StringVector det_names, SaveSpectrumAsType format) {
    SpecUtilsSwigJNI.SpecFile_write_to_file__SWIG_3(swigCPtr, this, filename, SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), StringVector.getCPtr(det_names), det_names, format.swigValue());
  }

  public void write(SWIGTYPE_p_std__ostream strm, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums, SaveSpectrumAsType format) {
    SpecUtilsSwigJNI.SpecFile_write__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(strm), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums), format.swigValue());
  }

  public void write(SWIGTYPE_p_std__ostream strm, SWIGTYPE_p_std__setT_int_t sample_nums, StringVector det_names, SaveSpectrumAsType format) {
    SpecUtilsSwigJNI.SpecFile_write__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(strm), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), StringVector.getCPtr(det_names), det_names, format.swigValue());
  }

  public boolean write_pcf(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.SpecFile_write_pcf(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public boolean write_2006_N42(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.SpecFile_write_2006_N42(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public boolean write_csv(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.SpecFile_write_csv(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public boolean write_txt(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.SpecFile_write_txt(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public boolean write_integer_chn(SWIGTYPE_p_std__ostream ostr, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums) {
    return SpecUtilsSwigJNI.SpecFile_write_integer_chn__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums));
  }

  public boolean write_integer_chn(SWIGTYPE_p_std__ostream ostr, SWIGTYPE_p_std__setT_int_t sample_nums, StringVector det_names) {
    return SpecUtilsSwigJNI.SpecFile_write_integer_chn__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), StringVector.getCPtr(det_names), det_names);
  }

  public boolean write_binary_spc(SWIGTYPE_p_std__ostream ostr, SpecFile.SpcBinaryType type, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums) {
    return SpecUtilsSwigJNI.SpecFile_write_binary_spc(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr), type.swigValue(), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums));
  }

  public boolean write_ascii_spc(SWIGTYPE_p_std__ostream output, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums) {
    return SpecUtilsSwigJNI.SpecFile_write_ascii_spc(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums));
  }

  public boolean write_binary_exploranium_gr130v0(SWIGTYPE_p_std__ostream output) {
    return SpecUtilsSwigJNI.SpecFile_write_binary_exploranium_gr130v0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output));
  }

  public boolean write_binary_exploranium_gr135v2(SWIGTYPE_p_std__ostream output) {
    return SpecUtilsSwigJNI.SpecFile_write_binary_exploranium_gr135v2(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output));
  }

  public boolean write_iaea_spe(SWIGTYPE_p_std__ostream output, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums) {
    return SpecUtilsSwigJNI.SpecFile_write_iaea_spe(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums));
  }

  public boolean write_cnf(SWIGTYPE_p_std__ostream output, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums) {
    return SpecUtilsSwigJNI.SpecFile_write_cnf(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums));
  }

  public boolean write_tka(SWIGTYPE_p_std__ostream output, SWIGTYPE_p_std__setT_int_t sample_nums, SWIGTYPE_p_std__setT_int_t det_nums) {
    return SpecUtilsSwigJNI.SpecFile_write_tka(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output), SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), SWIGTYPE_p_std__setT_int_t.getCPtr(det_nums));
  }

  public boolean write_d3_html(SWIGTYPE_p_std__ostream output, D3SpectrumChartOptions options, SWIGTYPE_p_std__setT_int_t sample_nums, StringVector det_names) {
    return SpecUtilsSwigJNI.SpecFile_write_d3_html(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output), D3SpectrumChartOptions.getCPtr(options), options, SWIGTYPE_p_std__setT_int_t.getCPtr(sample_nums), StringVector.getCPtr(det_names), det_names);
  }

  public SWIGTYPE_p_std__shared_ptrT_rapidxml__xml_documentT_char_t_t create_2012_N42_xml() {
    return new SWIGTYPE_p_std__shared_ptrT_rapidxml__xml_documentT_char_t_t(SpecUtilsSwigJNI.SpecFile_create_2012_N42_xml(swigCPtr, this), true);
  }

  public boolean write_2012_N42(SWIGTYPE_p_std__ostream ostr) {
    return SpecUtilsSwigJNI.SpecFile_write_2012_N42(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostr));
  }

  public SWIGTYPE_p_std__recursive_mutex mutex() {
    return new SWIGTYPE_p_std__recursive_mutex(SpecUtilsSwigJNI.SpecFile_mutex(swigCPtr, this), false);
  }

  public final static class DerivedVariantToKeep {
    public final static SpecFile.DerivedVariantToKeep NonDerived = new SpecFile.DerivedVariantToKeep("NonDerived");
    public final static SpecFile.DerivedVariantToKeep Derived = new SpecFile.DerivedVariantToKeep("Derived");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static DerivedVariantToKeep swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + DerivedVariantToKeep.class + " with value " + swigValue);
    }

    private DerivedVariantToKeep(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private DerivedVariantToKeep(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private DerivedVariantToKeep(String swigName, DerivedVariantToKeep swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static DerivedVariantToKeep[] swigValues = { NonDerived, Derived };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class CleanupAfterLoadFlags {
    public final static SpecFile.CleanupAfterLoadFlags RebinToCommonBinning = new SpecFile.CleanupAfterLoadFlags("RebinToCommonBinning", SpecUtilsSwigJNI.SpecFile_RebinToCommonBinning_get());
    public final static SpecFile.CleanupAfterLoadFlags DontChangeOrReorderSamples = new SpecFile.CleanupAfterLoadFlags("DontChangeOrReorderSamples", SpecUtilsSwigJNI.SpecFile_DontChangeOrReorderSamples_get());
    public final static SpecFile.CleanupAfterLoadFlags ReorderSamplesByTime = new SpecFile.CleanupAfterLoadFlags("ReorderSamplesByTime", SpecUtilsSwigJNI.SpecFile_ReorderSamplesByTime_get());
    public final static SpecFile.CleanupAfterLoadFlags StandardCleanup = new SpecFile.CleanupAfterLoadFlags("StandardCleanup", SpecUtilsSwigJNI.SpecFile_StandardCleanup_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static CleanupAfterLoadFlags swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + CleanupAfterLoadFlags.class + " with value " + swigValue);
    }

    private CleanupAfterLoadFlags(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private CleanupAfterLoadFlags(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private CleanupAfterLoadFlags(String swigName, CleanupAfterLoadFlags swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static CleanupAfterLoadFlags[] swigValues = { RebinToCommonBinning, DontChangeOrReorderSamples, ReorderSamplesByTime, StandardCleanup };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class SpcBinaryType {
    public final static SpecFile.SpcBinaryType IntegerSpcType = new SpecFile.SpcBinaryType("IntegerSpcType");
    public final static SpecFile.SpcBinaryType FloatSpcType = new SpecFile.SpcBinaryType("FloatSpcType");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SpcBinaryType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SpcBinaryType.class + " with value " + swigValue);
    }

    private SpcBinaryType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SpcBinaryType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SpcBinaryType(String swigName, SpcBinaryType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SpcBinaryType[] swigValues = { IntegerSpcType, FloatSpcType };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
