/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public final class SpectrumType {
  public final static SpectrumType Foreground = new SpectrumType("Foreground");
  public final static SpectrumType SecondForeground = new SpectrumType("SecondForeground");
  public final static SpectrumType Background = new SpectrumType("Background");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SpectrumType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SpectrumType.class + " with value " + swigValue);
  }

  private SpectrumType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SpectrumType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SpectrumType(String swigName, SpectrumType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SpectrumType[] swigValues = { Foreground, SecondForeground, Background };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

