/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public interface SpecUtilsSwigConstants {
  public final static int PERFORM_DEVELOPER_CHECKS = SpecUtilsSwigJNI.PERFORM_DEVELOPER_CHECKS_get();
  public final static int SpecUtils_ENABLE_D3_CHART = SpecUtilsSwigJNI.SpecUtils_ENABLE_D3_CHART_get();
  public final static int SpecUtils_ENABLE_URI_SPECTRA = SpecUtilsSwigJNI.SpecUtils_ENABLE_URI_SPECTRA_get();
  public final static int SpecUtils_USE_WT_THREADPOOL = SpecUtilsSwigJNI.SpecUtils_USE_WT_THREADPOOL_get();
  public final static int SpecUtils_USING_NO_THREADING = SpecUtilsSwigJNI.SpecUtils_USING_NO_THREADING_get();
  public final static int SpecUtils_D3_SUPPORT_FILE_STATIC = SpecUtilsSwigJNI.SpecUtils_D3_SUPPORT_FILE_STATIC_get();
  public final static int SpecUtils_INJA_TEMPLATES = SpecUtilsSwigJNI.SpecUtils_INJA_TEMPLATES_get();
  public final static int SpecUtils_BUILD_FUZZING_TESTS = SpecUtilsSwigJNI.SpecUtils_BUILD_FUZZING_TESTS_get();
  public final static int SpecUtils_PYTHON_BINDINGS = SpecUtilsSwigJNI.SpecUtils_PYTHON_BINDINGS_get();
  public final static int SpecUtils_JAVA_SWIG = SpecUtilsSwigJNI.SpecUtils_JAVA_SWIG_get();
  public final static int SpecUtils_USE_SIMD = SpecUtilsSwigJNI.SpecUtils_USE_SIMD_get();
  public final static int SpecUtils_ENABLE_EQUALITY_CHECKS = SpecUtilsSwigJNI.SpecUtils_ENABLE_EQUALITY_CHECKS_get();
  public final static int SpecUtils_USE_FROM_CHARS = SpecUtilsSwigJNI.SpecUtils_USE_FROM_CHARS_get();
  public final static int SpecFile_2012N42_VERSION = SpecUtilsSwigJNI.SpecFile_2012N42_VERSION_get();
}
