/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.sandia.specutils;

public class StringVector extends java.util.AbstractList<String> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StringVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpecUtilsSwigJNI.delete_StringVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public StringVector(String[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (String element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public StringVector(Iterable<String> initialElements) {
    this();
    for (String element : initialElements) {
      doAdd(element);
    }
  }

  public String get(int index) {
    return doGet(index);
  }

  public String set(int index, String e) {
    return doSet(index, e);
  }

  public boolean add(String e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, String e) {
    modCount++;
    doAdd(index, e);
  }

  public String remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public StringVector() {
    this(SpecUtilsSwigJNI.new_StringVector__SWIG_0(), true);
  }

  public StringVector(StringVector other) {
    this(SpecUtilsSwigJNI.new_StringVector__SWIG_1(StringVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return SpecUtilsSwigJNI.StringVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SpecUtilsSwigJNI.StringVector_clear(swigCPtr, this);
  }

  public StringVector(int count, String value) {
    this(SpecUtilsSwigJNI.new_StringVector__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return SpecUtilsSwigJNI.StringVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    SpecUtilsSwigJNI.StringVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return SpecUtilsSwigJNI.StringVector_doSize(swigCPtr, this);
  }

  private void doAdd(String x) {
    SpecUtilsSwigJNI.StringVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, String x) {
    SpecUtilsSwigJNI.StringVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private String doRemove(int index) {
    return SpecUtilsSwigJNI.StringVector_doRemove(swigCPtr, this, index);
  }

  private String doGet(int index) {
    return SpecUtilsSwigJNI.StringVector_doGet(swigCPtr, this, index);
  }

  private String doSet(int index, String val) {
    return SpecUtilsSwigJNI.StringVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SpecUtilsSwigJNI.StringVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
